mcrouter_SRC += \
    $(mcrouter_BASE)/app/private/ConsoleService.cpp             \
    $(mcrouter_BASE)/app/private/MulticastRouter.cpp            \
    $(mcrouter_BASE)/app/private/NEMulticastRouterSettings.cpp  \
    $(mcrouter_BASE)/app/private/posix/ConsoleServicePosix.cpp  \
    $(mcrouter_BASE)/app/private/posix/MulticastRouterPosix.cpp \
    $(mcrouter_BASE)/app/private/win32/ConsoleServiceWin32.cpp  \
    $(mcrouter_BASE)/app/private/win32/MulticastRouterWin32.cpp \
