mcrouter_SRC += \
    $(mcrouter_BASE)/app/private/MulticastRouter.cpp            \
    $(mcrouter_BASE)/app/private/NEMulticastRouterSettings.cpp 	\
    $(mcrouter_BASE)/app/private/Statistics.cpp					\
    $(mcrouter_BASE)/app/private/posix/MulticastRouterPosix.cpp	\
    $(mcrouter_BASE)/app/private/posix/StatisticsPosix.cpp		\
    $(mcrouter_BASE)/app/private/win32/MulticastRouterWin32.cpp	\
    $(mcrouter_BASE)/app/private/win32/StatisticsWin32.cpp		\
