mcrouter_SRC += \
    $(mcrouter_BASE)/app/private/Console.cpp                    \
    $(mcrouter_BASE)/app/private/ConsoleService.cpp             \
    $(mcrouter_BASE)/app/private/MulticastRouter.cpp            \
    $(mcrouter_BASE)/app/private/NEMulticastRouterSettings.cpp  \
    $(mcrouter_BASE)/app/private/posix/ConsolePosix.cpp         \
    $(mcrouter_BASE)/app/private/posix/MulticastRouterPosix.cpp \
    $(mcrouter_BASE)/app/private/win32/ConsoleWin32.cpp         \
    $(mcrouter_BASE)/app/private/win32/MulticastRouterWin32.cpp \
