#ifndef AREG_BASE_UTILITYDEFS_HPP
#define AREG_BASE_UTILITYDEFS_HPP
/************************************************************************
 * This file is part of the Areg SDK core engine.
 * Areg SDK is dual-licensed under Free open source (Apache version 2.0
 * License) and Commercial (with various pricing models) licenses, depending
 * on the nature of the project (commercial, research, academic or free).
 * You should have received a copy of the Areg SDK license description in LICENSE.txt.
 * If not, please contact to info[at]areg.tech
 *
 * \copyright   (c) 2017-2026 Aregtech UG. All rights reserved.
 * \file        areg/base/UtilityDefs.hpp
 * \ingroup     Areg SDK, Automated Real-time Event Grid Software Development Kit 
 * \author      Artak Avetyan
 * \brief       Areg Platform, Utilities
 *              Helper functions and constants.
 *
 ************************************************************************/
/************************************************************************
 * Include files.
 ************************************************************************/
#include "areg/base/areg_global.h"
#include "areg/base/MathDefs.hpp"

#include <chrono>
#include <string_view>
#include <utility>

/************************************************************************
 * Dependencies
 ************************************************************************/
struct tm;

namespace areg {
    class String;
    class InStream;
    class OutStream;
} // namespace areg

//////////////////////////////////////////////////////////////////////////
// Utility methods declaration
//////////////////////////////////////////////////////////////////////////
/**
 * \brief   Collection of helper functions and constants.
 *          For details see description of constants and functions.
 *
 **/
namespace areg {
/************************************************************************/
// areg namespace predefined constants
/************************************************************************/

    /**
     * \brief   areg::TIME_FORMAT_ISO8601_OUTPUT
     *          The format to display the time in microseconds, ISO8601 standard
     **/
    constexpr std::string_view  TIME_FORMAT_ISO8601_OUTPUT  { "%Y-%m-%d %H:%M:%S,%l" };
    /**
     * \brief   areg::TIME_FORMAT_ISO8601
     *          Short name of TIME_FORMAT_ISO8601_OUTPUT
     **/
    constexpr std::string_view  TIME_FORMAT_ISO8601         { "ISO8601" };

     /**
      * \brief   areg::TIME_FORMAT_ABSOLUTE_OUTPUT
      *          The format to display only the absolute time in milliseconds
      **/
    constexpr std::string_view  TIME_FORMAT_ABSOLUTE_OUTPUT{ "%H:%M:%S,%l" };
    /**
     * \brief   areg::TIME_FORMAT_ABSOLUTE
     *          Short name of TIME_FORMAT_ABSOLUTE_OUTPUT
     **/
    constexpr std::string_view  TIME_FORMAT_ABSOLUTE        { "ABSOLUTE" };

     /**
      * \brief   areg::TIME_FORMAT_DATE_OUTPUT
      *          The format to display the date, time and milliseconds
      **/
    constexpr std::string_view  TIME_FORMAT_DATE_OUTPUT     { "%d %b %Y %H:%M:%S,%l" };
    /**
     * \brief   areg::TIME_FORMAT_DATE
     *          Short name of TIME_FORMAT_DATE_OUTPUT
     **/
    constexpr std::string_view  TIME_FORMAT_DATE            { "DATE" };

    /**
     * \brief   Default time format
     **/
    constexpr std::string_view  DEFAULT_TIME_FORMAT         { areg::TIME_FORMAT_ISO8601 };
    /**
     * \brief   Default time format output
     **/
    constexpr std::string_view  DEFAULT_TIME_FORMAT_OUTPUT  { areg::TIME_FORMAT_ISO8601_OUTPUT };

    /**
     * \brief   areg::MAX_GENERATED_NAME_BUFFER_SIZE
     *          Constants. Predefined value, the maximum length of name
     *          generated by system.
     **/
    constexpr int32_t           MAX_GENERATED_NAME_BUFFER_SIZE  { 0xFF };

    /**
     * \brief   areg::DEFAULT_GENERATED_NAME
     *          Constant. Predefined default prefix for generated
     *          by system names.
     **/
    constexpr std::string_view      DEFAULT_GENERATED_NAME          	{ "name" };
    /**
     * \brief   areg::ITEM_NAMES_MAX_LENGTH
     *          The maximum length of item names such as thread name, component or service names
     **/
    constexpr uint32_t          ITEM_NAMES_MAX_LENGTH           	    { 64 };

    /**
     * \brief   areg::WIN_TO_POSIX_EPOCH_BIAS_MICROSECS
     *          The difference in microseconds between Windows and Unix epoch.
     **/
    constexpr TIME64                WIN_TO_POSIX_EPOCH_BIAS_MICROSECS	{11644473600000000LL};

    /**
     * \brief   areg::SEC_TO_MILLISECS
     *          Milliseconds in 1 second.
     **/
    constexpr TIME64                SEC_TO_MILLISECS                    { 1'000LL };

    /**
     * \brief   areg::SEC_TO_MICROSECS
     *          Microseconds in 1 second.
     **/
    constexpr TIME64                SEC_TO_MICROSECS                    { 1'000'000LL };

    /**
     * \brief   areg::MILLISEC_TO_MICROSECS
     *          Microseconds in 1 millisecond.
     **/
    constexpr TIME64                MILLISEC_TO_MICROSECS               { 1'000LL };

    /**
     * \brief   areg::MILLISEC_TO_100NS
     *          100 nanoseconds in 1 millisecond.
     **/
    constexpr TIME64                MILLISEC_TO_100NS                   { 10'000LL };

    /**
     * \brief   areg::MILLISEC_TO_NS
     *          Nanoseconds in 1 millisecond.
     **/
    constexpr TIME64                MILLISEC_TO_NS                      { 1'000'000LL };

    /**
     * \brief   areg::SEC_TO_NS
     *          Nanoseconds in 1 second.
     **/
    constexpr TIME64                SEC_TO_NS                      		{ 1'000'000'000LL };

    /**
     * \brief   areg::MICROSEC_TO_100NS
     *          100-nanoseconds in 1 microsecond.
     **/
    constexpr TIME64                MICROSEC_TO_100NS                   { 10LL };

    /**
     * \brief   areg::MICROSEC_TO_NS
     *          Nanoseconds in 1 microsecond.
     **/
    constexpr TIME64                MICROSEC_TO_NS                    	{ 1'000LL };

    /**
     * \brief   areg::MIN_TO_SECS
     *          Seconds in 1 minute.
     **/
    constexpr TIME64                MIN_TO_SECS                         { 60LL };

    /**
     * \brief   areg::MIN_TO_MILLISECS
     *          Milliseconds in 1 minute.
     **/
    constexpr TIME64                MIN_TO_MILLISECS                    { MIN_TO_SECS * SEC_TO_MILLISECS };

    /**
     * \brief   areg::MIN_TO_MICROSECS
     *          Microseconds in 1 minute.
     **/
    constexpr TIME64                MIN_TO_MICROSECS                    { MIN_TO_SECS * SEC_TO_MICROSECS };

    /**
     * \brief   areg::HOUR_TO_MINS
     *          Minutes in 1 hour.
     **/
    constexpr TIME64                HOUR_TO_MINS                        { 60LL };

    /**
     * \brief   areg::HOUR_TO_SECS
     *          Seconds in 1 hour.
     **/
    constexpr TIME64                HOUR_TO_SECS                        { HOUR_TO_MINS * MIN_TO_SECS };

    /**
     * \brief   areg::HOUR_TO_MILLISECS
     *          Milliseconds in 1 hour.
     **/
    constexpr TIME64                HOUR_TO_MILLISECS                   { HOUR_TO_SECS * SEC_TO_MILLISECS };

    /**
     * \brief   areg::HOUR_TO_MICROSECS
     *          Microseconds in 1 hour.
     **/
    constexpr TIME64                HOUR_TO_MICROSECS                   { HOUR_TO_SECS * SEC_TO_MICROSECS };

    /**
     * \brief   areg::DAY_TO_HOURS
     *          Hours in 1 day.
     **/
    constexpr TIME64                DAY_TO_HOURS                        { 24LL };

    /**
     * \brief   areg::DAY_TO_MINS
     *          Minutes in 1 day.
     **/
    constexpr TIME64                DAY_TO_MINS                         { DAY_TO_HOURS * HOUR_TO_MINS };

    /**
     * \brief   areg::DAY_TO_SECS
     *          Seconds in 1 day.
     **/
    constexpr TIME64                DAY_TO_SECS                         { DAY_TO_MINS * MIN_TO_SECS };

    /**
     * \brief   areg::DAY_TO_MILLISECS
     *          Milliseconds in 1 day.
     **/
    constexpr TIME64                DAY_TO_MILLISECS                    { DAY_TO_SECS * SEC_TO_MILLISECS };

    /**
     * \brief   areg::DAY_TO_MICROSECS
     *          Microseconds in 1 day.
     **/
    constexpr TIME64                DAY_TO_MICROSECS                    { DAY_TO_SECS * SEC_TO_MICROSECS };

    /**
     * \brief   areg::YEAR_TO_DAYS
     *          Days in 1 year.
     **/
    constexpr TIME64                YEAR_TO_DAYS                        { 365LL };

    /**
     * \brief   areg::YEAR_TO_HOURS
     *          Hours in 1 year.
     **/
    constexpr TIME64                YEAR_TO_HOURS                       { YEAR_TO_DAYS * DAY_TO_HOURS };

    /**
     * \brief   areg::YEAR_TO_MINS
     *          Minutes in 1 year.
     **/
    constexpr TIME64                YEAR_TO_MINS                        { YEAR_TO_HOURS * HOUR_TO_MINS};

    /**
     * \brief   areg::YEAR_TO_SECS
     *          Seconds in 1 year.
     **/
    constexpr TIME64                YEAR_TO_SECS                        { YEAR_TO_MINS * MIN_TO_SECS };

    /**
     * \brief   areg::YEAR_TO_MILLISECS
     *          Milliseconds in 1 year.
     **/
    constexpr TIME64                YEAR_TO_MILLISECS                   { YEAR_TO_SECS * SEC_TO_MILLISECS };

    /**
     * \brief   areg::YEAR_TO_MICROSECS
     *          Microseconds in 1 year.
     **/
    constexpr TIME64                YEAR_TO_MICROSECS                   { YEAR_TO_SECS * SEC_TO_MICROSECS };

    /**
     * \brief   areg::YEAR_TO_DAYS_EX
     *          Days in 1 leap year
     **/
    constexpr TIME64                YEAR_TO_DAYS_EX                     { 366LL };

    /**
     * \brief   areg::YEAR_TO_HOURS_EX
     *          Hours in 1 leap year.
     **/
    constexpr TIME64                YEAR_TO_HOURS_EX                    { YEAR_TO_DAYS_EX * DAY_TO_HOURS };

    /**
     * \brief   areg::YEAR_TO_MINS_EX
     *          Minutes in 1 leap year.
     **/
    constexpr TIME64                YEAR_TO_MINS_EX                     { YEAR_TO_HOURS_EX * HOUR_TO_MINS};

    /**
     * \brief   areg::YEAR_TO_SECS_EX
     *          Seconds in 1 leap year.
     **/
    constexpr TIME64                YEAR_TO_SECS_EX                     { YEAR_TO_MINS_EX * MIN_TO_SECS };

    /**
     * \brief   areg::YEAR_TO_MILLISECS_EX
     *          Milliseconds in 1 leap year.
     **/
    constexpr TIME64                YEAR_TO_MILLISECS_EX                { YEAR_TO_SECS_EX * SEC_TO_MILLISECS };

    /**
     * \brief   areg::YEAR_TO_MICROSECS_EX
     *          Microseconds in 1 leap year.
     **/
    constexpr TIME64                YEAR_TO_MICROSECS_EX                { YEAR_TO_SECS_EX * SEC_TO_MICROSECS };


/************************************************************************/
// areg namespace utility types
/************************************************************************/

    /**
     * \brief   Structure for date-time data used in system time.
     **/
    struct CalendarTime
    {
        int32_t     stYear{ 0 };        //!< The year in the time
        int32_t     stMonth{ 0 };       //!< The month in the time, which starts from 1 (January) until 12 (December)
        int32_t     stDayOfWeek{ 0 };   //!< The day of week in the time, which starts from 1 (Sunday) until 7 (Saturday)
        int32_t     stDayOfYear{ 0 };   //!< The day of the year, which starts from 1 to 365
        int32_t     stDay{ 0 };         //!< The day of the month in the time, which starts from 1
        int32_t     stHour{ 0 };        //!< The hour in the time, which starts from 0
        int32_t     stMinute{ 0 };      //!< The minute in the time, which starts from 0
        int32_t     stSecond{ 0 };      //!< The second in the time, which starts from 0
        int32_t     stMillisecs{ 0 };   //!< The millisecond in the time, which starts from 0
        int32_t     stMicrosecs{ 0 };   //!< The microseconds in the time, which starts from 0
    };

    /**
     * \brief   Converts time in microseconds to time in seconds.
     * \param   microsecs   The time in microseconds.
     * \return  Returns time in seconds.
     **/
    [[nodiscard]]
    inline constexpr time_t to_seconds(const TIME64 & microsecs) noexcept;

    /**
     * \brief   Converts the broken time to seconds, throwing out the milliseconds and microseconds.
     * \param   sysTime     The broken time to convert.
     * \return  Returns time in seconds.
     **/
    [[nodiscard]]
    inline constexpr time_t to_seconds(const CalendarTime& sysTime) noexcept;

    /**
     * \brief   Returns current time. On output 'out_sysTime' system time contains the date-time data.
     * \param[out]  sysTime     On output the system time parameter contains date-time of current time.
     * \param[in]   localTime   If true, in output the out_sysTime contains local time values.
     **/
    AREG_API void system_time_now( CalendarTime & sysTime, bool localTime ) noexcept;

    /**
     * \brief   Returns current system time data as a 64-bit integer value. The returned value is
     *          passed microseconds since January 1, 1970 (UNIX epoch).
     * \return  Returns microseconds passed since January 1, 1970 (UNIX epoch).
     **/
    [[nodiscard]]
    AREG_API TIME64 system_time_now() noexcept;

    /**
     * \brief   Returns system time data as a 64-bit integer value in microseconds passed since Unix epoch,
     *          which is January 1, 1970 (UNIX epoch).
     * \param   sysTime     The system time structure with data to convert.
     * \return  Returns microseconds passed since January 1, 1970 (UNIX epoch).
     **/
    [[nodiscard]]
    inline constexpr TIME64 to_time( const CalendarTime & sysTime ) noexcept;

    /**
     * \brief   Returns tm structure data as a 64-bit integer value in microseconds passed since Unix epoch,
     *          which is January 1, 1970 (UNIX epoch).
     * \param   time    The system time structure with data to convert.
     * \return  Returns microseconds passed since January 1, 1970 (UNIX epoch).
     **/
    [[nodiscard]]
    inline constexpr TIME64 to_time(const struct tm& time) noexcept;

    /**
     * \brief   Converts 64-bit value of microseconds passed since January 1 1970 into system time data structure.
     * \param[in]   timeValue   64-bit value as microseconds passed since January 1 1970.
     * \param[out]  sysTime     On output the system time parameter contains date-time of converted time.
     **/
    AREG_API void to_system_time( const TIME64 & timeValue, CalendarTime & sysTime ) noexcept;

    /**
     * \brief   Compare 2 system-time data structures and returns result indicating equality of data.
     * \param   lhs     Left-Hand Operand to compare
     * \param   rhs     Right-Hand Operand to compare
     * \return  Returns one of possible results: 
     *              - areg::Smaller if Left-Hand Operand 'lhs' is smaller than Right-Hand Operand 'rhs'
     *              - areg::Equal if both operands are equal
     *              - areg::Bigger  if Left-Hand Operand 'lhs' is greater than Right-Hand Operand 'rhs'
     **/
    [[nodiscard]]
    inline constexpr areg::Ordering compare_times( const CalendarTime & lhs, const CalendarTime & rhs ) noexcept;

    /**
     * \brief   Compare 2 64-bit time values and returns result indicating equality of data. The given 64-values
     *          are microseconds passed since 1 January 1970.
     * \param   lhs     Left-Hand Operand to compare
     * \param   rhs     Right-Hand Operand to compare
     * \return  Returns one of possible results:
     *              - areg::Smaller if Left-Hand Operand 'lhs' is smaller than Right-Hand Operand 'rhs'
     *              - areg::Equal if both operands are equal
     *              - areg::Bigger  if Left-Hand Operand 'lhs' is greater than Right-Hand Operand 'rhs'
     **/
    [[nodiscard]]
    inline constexpr areg::Ordering compare_times( const TIME64 & lhs, const TIME64 & rhs ) noexcept;

    /**
     * \brief   Converts given time in microseconds into the time in seconds, milliseconds and microseconds.
     *
     * \param[in]   time    The time in microseconds to parse and extract.
     * \param[out]  secs    On output, this contains the time in seconds.
     * \param[out]  milli   On output, this contains the remaining time in milliseconds.
     * \param[out]  micro   On output, this contains the remaining time in microseconds.
     **/
    inline constexpr void conv_microsecs(const TIME64 & time, time_t & secs, uint16_t & milli, uint16_t & micro) noexcept;

    /**
     * \brief   Converts system-time data structure to standard 'tm' type. In conversion, a milliseconds part of data will be lost.
     * \param[in]   sysTime     The system-time data structure to convert.
     * \param[out]  time        On output the parameter contains date-time of converted system time without information of milliseconds.
     **/
    inline void to_tm( const CalendarTime & sysTime, struct tm & time ) noexcept;

    /**
     * \brief   Converts time in microseconds since Unix epoch (January 1, 1970) to standard 'tm' type.
     *          In conversion, a milliseconds and microseconds part of data will be lost.
     * \param[in]   timeMicro   The time in microseconds since Unix epoch (January 1, 1970) to convert.
     * \param[out]  time        On output the parameter contains date-time of converted system time without information of milliseconds.
     **/
    AREG_API void to_tm(const TIME64& timeMicro, struct tm& time);

    /**
     * \brief   Converts standard 'tm' type to system-time data structure. In conversion, a milliseconds part of data will not exist.
     * \param[in]   time        Contains date-time of converted system time without information of milliseconds.
     * \param[out]  sysTime     On output, the parameter contains date-time information in system-time data structure format without millisecond information.
     **/
    inline constexpr void to_system_time( const struct tm & time, CalendarTime & sysTime ) noexcept;

    /**
     * \brief   Localizes the UTC time data value. On output the passed structure contains values in UTC timezone.
     * \param[in,out]   utcTime     The time structure in UTC time to convert.
     *                              On output the values of structure will be in local time zone.
     **/
    AREG_API void make_tm_local( struct tm & utcTime ) noexcept;

    /**
     * \brief   Returns the tick counts information in milliseconds since process has started.
     **/
    AREG_API TIME64 tick_count() noexcept;

    /**
     * \brief   Converts the system UTC time to local time.
     * \param[in]   utcTime     The UTC time to convert.
     * \param[out]  localTime   On output this structure contains the converted local time.
     * \return  Returns true if conversion succeeded.
     **/
    AREG_API bool to_local_time( const CalendarTime & utcTime, CalendarTime & localTime ) noexcept;

    /**
     * \brief   Converts the system UTC time to local time.
     * \param[in]   utcTime     The UTC time in microseconds passed since January 1 1970
     * \param[out]  localTime   On return this structure contains the local time information.
     * \return  Returns true if conversion succeeded.
     **/
    AREG_API bool to_local_time( const TIME64 & utcTime, CalendarTime & localTime ) noexcept;

    /**
     * \brief   Converts the system UTC time to local time in structure of tm.
     * \param[in]   utcTime     The UTC time in microseconds passed since January 1 1970
     * \param[out]  localTm     On return this structure contains the local time information.
     * \return  Returns true if conversion succeeded.
     **/
    AREG_API bool to_local_tm(const TIME64 & utcTime, struct tm & localTm) noexcept;

/************************************************************************/
// areg namespace utility functions, generate names
/************************************************************************/
    /**
     * \brief   Creates Component item name separating by COMPONENT_ITEM_SEPARATOR if component name is given.
     *          Otherwise, it will return itemName
     * \param   componentName   The name of item parent component, normally component role name
     * \param   itemName        The name of component item.
     * \return  Returns created new string containing componentName and itemName separated by COMPONENT_ITEM_SEPARATOR.
     **/
    [[nodiscard]]
    AREG_API String create_component_item_name(const String & componentName, const String & itemName);

    /**
     * \brief   This function generates and returns name 
     *          using time-stamp value in nanoseconds in the name.
     *          If passed prefix is nullptr, it will use predefined
     *          areg::DEFAULT_GENERATED_NAME constant as a
     *          prefix for name. The maximum length of generated
     *          name is areg::MAX_GENERATED_NAME_BUFFER_SIZE.
     *          To provide uniqueness for generated name, make
     *          sure that the length of passed prefix is not
     *          more than (areg::MAX_GENERATED_NAME_BUFFER_SIZE - 34)
     * \param   prefix  The prefix to add in generated name.
     *                  If this value is nullptr it will use
     *                  areg::DEFAULT_GENERATED_NAME as
     *                  a prefix for name.
     * \return  Returns system generated unique name.
     **/
    [[nodiscard]]
    AREG_API String generate_name( const char * prefix );

    /**
     * \brief   This function generates and returns name 
     *          using time-stamp value in nanoseconds in the name.
     *          If passed prefix is nullptr, it will use predefined
     *          areg::DEFAULT_GENERATED_NAME constant as a
     *          prefix for name. Before calling this function,
     *          the output buffer should be allocated and the length
     *          of buffer should be big enough to contain prefix
     *          and the time-stamp. The time-stamp requires at least
     *          34 characters. Generated output name is in 
     *          format <prefix>:{nn:nn:nn:nn:nn:nn:nn:nn})
     * \param[in]   prefix      The prefix to add in generated name.
     *                          If this value is nullptr it will use
     *                          areg::DEFAULT_GENERATED_NAME as
     *                          a prefix for name.
     * \param[out]   buffer     The output buffer to fill generated name.
     *                          The length of buffer should be big enough
     *                          to contain prefix and prefix.
     * \param[in]   length      The length of buffer to set name.
     * \return  Returns the content of 'buffer'. If 'buffer' is invalid, returns nullptr.
     **/
    AREG_API const char * generate_name( const char * prefix, char * buffer, int32_t length) noexcept;

    /**
     * \brief   This function generates and returns name 
     *          using time-stamp value in nanoseconds in the name.
     *          If passed prefix is nullptr, it will use predefined
     *          areg::DEFAULT_GENERATED_NAME constant as a
     *          prefix for name. Before calling this function,
     *          the output buffer should be allocated and the length
     *          of buffer should be big enough to contain prefix
     *          and the time-stamp. The time-stamp requires at least
     *          34 characters. Generated output name is in 
     *          format <prefix>:{nn:nn:nn:nn:nn:nn:nn:nn})
     * \param[in]   prefix      The prefix to add in generated name.
     *                          If this value is nullptr it will use
     *                          areg::DEFAULT_GENERATED_NAME as
     *                          a prefix for name.
     * \param[out]  buffer      The output buffer to fill generated name.
     *                          The length of buffer should be big enough
     *                          to contain prefix and prefix.
     * \param[in]   length      The length of buffer to set name.
     * \param[in]   specChar    Special character used in generated name.
     * \return  Returns the content of 'buffer'. If 'buffer' is invalid, returns nullptr.
     **/
    AREG_API const char * generate_name( const char * prefix, char * buffer, int32_t length, const char * specChar) noexcept;

/************************************************************************/
// areg namespace utility functions, generate unique ID
/************************************************************************/
    /**
     * \brief	Generates and returns unique uint32_t value
     **/
    [[nodiscard]]
    AREG_API uint32_t generate_unique_id() noexcept;

    //!< The data rate type
    using DataLiteral = std::pair<double, std::string_view>;

    /**
     * \brief   Converts the data size in bytes value into readable values bytes, kilobytes or megabytes.
     *          In the returned pair type, first parameter contains converted size and the second
     *          contains the string literal of the size.
     * 
     * \param   dataSize    The data size in bytes to convert.
     * \return  Returns a pair where the first value contains converted size and
     *          the second value is the string literal of converted size. For example,
     *          the value 2500 bytes is converted in pairs <2.5, 'KBytes'>, i.e. 2.5 kilobytes.
     */
    [[nodiscard]]
    AREG_API DataLiteral conv_data_size( uint64_t dataSize );

    /**
     * \brief   Converts the time duration in nanoseconds value into readable values nanoseconds,
     *          microseconds, milliseconds or seconds.
     *          In the returned pair type, first parameter contains converted duration and the second
     *          contains the string literal of the duration.
     *
     * \param   timeDuration    The time duration in nanoseconds to convert.
     * \return  Returns a pair where the value is converted time and the second value
     *          is a literal of the converted time. For example, the value 2500 is
     *          converted into pair <2.5, 'us'>, i.e. 2.5 microseconds.
     */
    [[nodiscard]]
    AREG_API DataLiteral conv_duration( uint64_t timeDuration );

    /**
     * \brief   High-resolution stopwatch for measuring elapsed time. Call start() to begin timing,
     *          stop() to capture the end time, and accessor methods to retrieve durations in
     *          various units.
      *
      * \example Use of areg::Duration:
      *
      *          areg::Duration stopWatch;
      *          stopWatch.stop();
      *          std::cout << "Time passed " << stopWatch.passed_milliseconds() << " ms" << std::endl;
      *
      *          std::cout << "Started new timer at epoch time " << stopWatch.start() << std::endl;
      *          std::cout << "Stopped timer at epoch time " << stopWatch.stop() << std::endl;
      *          std::cout << "Time passed: " << stopWatch.passed_nanoseconds() << " ns" << std::endl;
     **/
    class AREG_API Duration
    {
    //////////////////////////////////////////////////////////////////////////
    // Constructors / Destructor, operators
    //////////////////////////////////////////////////////////////////////////
    public:
        inline Duration() noexcept;

        constexpr Duration( const Duration & src ) noexcept = default;

        ~Duration() noexcept = default;

        constexpr Duration & operator = ( const Duration & src ) noexcept = default;

    //////////////////////////////////////////////////////////////////////////
    // Operations, attributes.
    //////////////////////////////////////////////////////////////////////////
    public:

        /**
         * \brief   Starts the timer. Call stop() to calculate duration.
         *
         * \return  Returns the starting time in nanoseconds since epoch.
         **/
        inline TIME64 mark_start() noexcept;

        /**
         * \brief   Stops the timer and returns the stop time in nanoseconds since epoch.
         *
         * \return  Returns the stop time in nanoseconds since epoch.
         **/
        inline TIME64 mark_stop() noexcept;

        /**
         * \brief   Returns the recorded start time in nanoseconds since epoch.
         **/
        inline constexpr TIME64 start() const noexcept;

        /**
         * \brief   Returns the recorded stop time in nanoseconds since epoch.
         **/
        inline constexpr TIME64 stop() const noexcept;

        /**
         * \brief   Returns the elapsed time in nanoseconds.
         **/
        [[nodiscard]]
        inline constexpr uint64_t passed_nanoseconds() const noexcept;

        /**
         * \brief   Returns the elapsed time in microseconds.
         **/
        [[nodiscard]]
        inline constexpr uint64_t passed_microseconds() const noexcept;

        /**
         * \brief   Returns the elapsed time in milliseconds.
         **/
        [[nodiscard]]
        inline constexpr uint64_t passed_milliseconds() const noexcept;

        /**
         * \brief   Returns the elapsed time in seconds.
         **/
        [[nodiscard]]
        inline constexpr uint64_t passed_seconds() const noexcept;

        /**
         * \brief   Returns the elapsed time in minutes.
         **/
        [[nodiscard]]
        inline constexpr uint64_t passed_minutes() const noexcept;

        /**
         * \brief   Returns the elapsed time in nanoseconds since the watch was started. If stop()
         *          was called, returns the duration between start and stop. Otherwise, returns the
         *          duration from start to now.
         **/
        [[nodiscard]]
        inline uint64_t duration_since_start() const noexcept;

    //////////////////////////////////////////////////////////////////////////
    // Member variables
    //////////////////////////////////////////////////////////////////////////
    private:
#if defined(_MSC_VER) && (_MSC_VER > 1200)
    #pragma warning(disable: 4251)
#endif  // _MSC_VER
        //!< The high-resolution starting time since epoch.
        std::chrono::steady_clock::time_point   mStart;
        //!< The high-resolution stopping time since epoch.
        std::chrono::steady_clock::time_point   mStop;
#if defined(_MSC_VER) && (_MSC_VER > 1200)
    #pragma warning(default: 4251)
#endif  // _MSC_VER
    };

    /**
     * \brief   Converts given value to pointer type ToPtr.
     *          If ToPtr is not a pointer type, it will convert
     *          the value to the given type.
     * \tparam  ToPtr       The type to convert. If this is a pointer type,
     *                      it will convert the value to pointer.
     * \tparam  FromType    The type of value to convert.
     * \param   value       The value to convert.
     * \return  Returns converted value to pointer type ToPtr. If ToPtr is not
     *          a pointer type, it will convert the value to the given type.
     **/
    template <typename ToPtr, typename FromType>
    inline constexpr ToPtr to_ptr( FromType value ) noexcept;

    /**
     * \brief   Converts given pointer or value to numeric type ToNum.
     *          If FromType is a pointer type, it will convert
     *          the pointer to numeric value. Otherwise, it will
     *          convert the value to the given type.
     * \tparam  ToNum       The numeric type to convert.
     * \tparam  FromType    The type of value to convert. If this is a pointer type,
     *                      it will convert the pointer to numeric value.
     * \param   ptrValue    The pointer or value to convert.
     * \return  Returns converted pointer or value to numeric type ToNum.
     **/
    template <typename ToNum, typename FromType>
    inline constexpr ToNum to_num( FromType ptrValue ) noexcept;
} // namespace areg

//////////////////////////////////////////////////////////////////////////
// areg::Duration inline methods
//////////////////////////////////////////////////////////////////////////

inline constexpr time_t areg::to_seconds(const TIME64& microsecs) noexcept
{
    return static_cast<time_t>(microsecs / areg::SEC_TO_MICROSECS);
}

inline constexpr time_t areg::to_seconds(const areg::CalendarTime & sysTime) noexcept
{
    const int32_t year{ sysTime.stYear - 1900 };

    return    static_cast<time_t>(sysTime.stSecond)
            + static_cast<time_t>(static_cast<TIME64>(sysTime.stMinute       ) * areg::MIN_TO_SECS)
            + static_cast<time_t>(static_cast<TIME64>(sysTime.stHour         ) * areg::HOUR_TO_SECS)
            + static_cast<time_t>(static_cast<TIME64>(sysTime.stDayOfYear - 1) * areg::DAY_TO_SECS)
            + static_cast<time_t>(static_cast<TIME64>( year -  70            ) * areg::YEAR_TO_SECS)
            + static_cast<time_t>(static_cast<TIME64>((year -  69) /   4     ) * areg::DAY_TO_SECS)
            - static_cast<time_t>(static_cast<TIME64>((year -   1) / 100     ) * areg::DAY_TO_SECS)
            + static_cast<time_t>(static_cast<TIME64>((year + 299) / 400     ) * areg::DAY_TO_SECS);
}

inline constexpr TIME64 areg::to_time(const areg::CalendarTime& sysTime) noexcept
{
    const int32_t year{ sysTime.stYear - 1900 };

    return    static_cast<TIME64>(sysTime.stMicrosecs)
            + static_cast<TIME64>(sysTime.stMillisecs    ) * areg::MILLISEC_TO_MICROSECS
            + static_cast<TIME64>(sysTime.stSecond       ) * areg::SEC_TO_MICROSECS
            + static_cast<TIME64>(sysTime.stMinute       ) * areg::MIN_TO_MICROSECS
            + static_cast<TIME64>(sysTime.stHour         ) * areg::HOUR_TO_MICROSECS
            + static_cast<TIME64>(sysTime.stDayOfYear - 1) * areg::DAY_TO_MICROSECS
            + static_cast<TIME64>( year -  70            ) * areg::YEAR_TO_MICROSECS
            + static_cast<TIME64>((year -  69) /   4     ) * areg::DAY_TO_MICROSECS
            - static_cast<TIME64>((year -   1) / 100     ) * areg::DAY_TO_MICROSECS
            + static_cast<TIME64>((year + 299) / 400     ) * areg::DAY_TO_MICROSECS;
}

inline constexpr TIME64 areg::to_time(const tm& time) noexcept
{
    return    static_cast<TIME64>(time.tm_sec               ) * areg::SEC_TO_MICROSECS
            + static_cast<TIME64>(time.tm_min               ) * areg::MIN_TO_MICROSECS
            + static_cast<TIME64>(time.tm_hour              ) * areg::HOUR_TO_MICROSECS
            + static_cast<TIME64>(time.tm_yday              ) * areg::DAY_TO_MICROSECS
            + static_cast<TIME64>(time.tm_year - 70         ) * areg::YEAR_TO_MICROSECS
            + static_cast<TIME64>((time.tm_year - 69)  / 4  ) * areg::DAY_TO_MICROSECS
            - static_cast<TIME64>((time.tm_year - 1)   / 100) * areg::DAY_TO_MICROSECS
            + static_cast<TIME64>((time.tm_year + 299) / 400) * areg::DAY_TO_MICROSECS;
}

//////////////////////////////////////////////////////////////////////////
// areg::Duration inline methods
//////////////////////////////////////////////////////////////////////////

inline areg::Duration::Duration() noexcept
    : mStart        ( std::chrono::steady_clock::now() )
    , mStop         ( mStart )
{
}

inline TIME64 areg::Duration::mark_start() noexcept
{
    mStart      = std::chrono::steady_clock::now();
    mStop       = mStart;

    return static_cast<TIME64>(mStart.time_since_epoch( ).count( ));
}

inline TIME64 areg::Duration::mark_stop() noexcept
{
    if ( mStop == mStart )
    {
        mStop = std::chrono::steady_clock::now( );
    }

    return static_cast<TIME64>(mStop.time_since_epoch( ).count( ));
}

inline constexpr TIME64 areg::Duration::start() const noexcept
{
    return static_cast<TIME64>(mStart.time_since_epoch( ).count( ));
}

inline constexpr TIME64 areg::Duration::stop() const noexcept
{
    return static_cast<TIME64>(mStop.time_since_epoch( ).count( ));
}

inline constexpr uint64_t areg::Duration::passed_nanoseconds() const noexcept
{
    return static_cast<uint64_t>((mStop - mStart).count());
}

inline constexpr uint64_t areg::Duration::passed_microseconds() const noexcept
{
    return static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::microseconds>(mStop - mStart).count());
}

inline constexpr uint64_t areg::Duration::passed_milliseconds() const noexcept
{
    return static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(mStop - mStart).count( ));
}

inline constexpr uint64_t areg::Duration::passed_seconds() const noexcept
{
    return static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::seconds>(mStop - mStart).count( ));
}

inline constexpr uint64_t areg::Duration::passed_minutes() const noexcept
{
    return static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::minutes>(mStop - mStart).count( ));
}

inline uint64_t areg::Duration::duration_since_start() const noexcept
{
    return static_cast<uint64_t>((mStop > mStart ? (mStop - mStart).count( ) : (std::chrono::steady_clock::now( ) - mStart).count( )));
}

template <typename ToPtr, typename FromType>
inline constexpr ToPtr areg::to_ptr( FromType ptrValue ) noexcept
{
    if constexpr (std::is_pointer_v<ToPtr>)
    {
        return reinterpret_cast<ToPtr>(static_cast<std::uintptr_t>(ptrValue));
    }
    else
    {
        return static_cast<ToPtr>(ptrValue);
    }
}

template<typename ToNum, typename FromType>
inline constexpr ToNum areg::to_num(FromType value) noexcept
{
    if constexpr (std::is_pointer_v<FromType>)
    {
        return static_cast<ToNum>(reinterpret_cast<std::uintptr_t>(value));
    }
    else
    {
        return static_cast<ToNum>(value);
    }
}

inline constexpr areg::Ordering areg::compare_times( const TIME64 & lhs, const TIME64 & rhs ) noexcept
{
    areg::Int64Parts lhsLi{};
    areg::Int64Parts rshLi{};
    lhsLi.quadPart = lhs;
    rshLi.quadPart = rhs;
    return areg::compare_parts(lhsLi, rshLi);
}

inline constexpr areg::Ordering areg::compare_times( const areg::CalendarTime & lhs, const areg::CalendarTime & rhs ) noexcept
{
    const TIME64 lhsTm{ areg::to_time(lhs) };
    const TIME64 rshTm{ areg::to_time(rhs) };
    return (lhsTm > rshTm ? areg::Ordering::Bigger : (lhsTm < rshTm ? areg::Ordering::Smaller : areg::Ordering::Equal));
}

inline constexpr void areg::conv_microsecs( const TIME64 & time, time_t & secs, uint16_t & milli, uint16_t & micro ) noexcept
{
    secs  = static_cast<time_t>(time / areg::SEC_TO_MICROSECS);
    const TIME64 rest{ time % areg::SEC_TO_MICROSECS };
    milli = static_cast<uint16_t>(rest / areg::MILLISEC_TO_MICROSECS);
    micro = static_cast<uint16_t>(rest % areg::MILLISEC_TO_MICROSECS);
}

inline void areg::to_tm( const areg::CalendarTime & sysTime, struct tm & time ) noexcept
{
    if (sysTime.stYear >= 1900)
    {
        time.tm_sec     = static_cast<int32_t>(sysTime.stSecond);
        time.tm_min     = static_cast<int32_t>(sysTime.stMinute);
        time.tm_hour    = static_cast<int32_t>(sysTime.stHour);
        time.tm_mday    = static_cast<int32_t>(sysTime.stDay);
        time.tm_mon     = static_cast<int32_t>(sysTime.stMonth     -    1);    // tm_mon is 0-based
        time.tm_year    = static_cast<int32_t>(sysTime.stYear      - 1900);    // tm_year is 1900-based
        time.tm_wday    = static_cast<int32_t>(sysTime.stDayOfWeek -    1);    // tm_wday is 0-based
        time.tm_yday    = static_cast<int32_t>(sysTime.stDayOfYear -    1);    // day of year 0-based
        time.tm_isdst   = -1;
    }
    else
    {
        ASSERT( false );
        time = {};
    }
}

inline constexpr void areg::to_system_time( const struct tm & time, areg::CalendarTime & sysTime ) noexcept
{
    sysTime.stSecond    = static_cast<int32_t>(time.tm_sec);
    sysTime.stMinute    = static_cast<int32_t>(time.tm_min);
    sysTime.stHour      = static_cast<int32_t>(time.tm_hour);
    sysTime.stDay       = static_cast<int32_t>(time.tm_mday);
    sysTime.stMonth     = static_cast<int32_t>(time.tm_mon  +    1);
    sysTime.stYear      = static_cast<int32_t>(time.tm_year + 1900);
    sysTime.stDayOfWeek = static_cast<int32_t>(time.tm_wday +    1);
    sysTime.stDayOfYear = static_cast<int32_t>(time.tm_yday +    1);
}

#endif  // AREG_BASE_UTILITYDEFS_HPP
