13_common_SRC  += \
    $(13_pubmesh_BASE)/common/src/LocalHelloWorldClient.cpp		\
    $(13_pubmesh_BASE)/common/src/LocalHelloWorldService.cpp	\
    $(13_pubmesh_BASE)/common/src/PublicHelloWorldClient.cpp	\
    $(13_pubmesh_BASE)/common/src/PublicHelloWorldService.cpp
