
//////////////////////////////////////////////////////////////////////////
// Begin generate TrafficLightFSM.cpp file
//////////////////////////////////////////////////////////////////////////

/************************************************************************
 * (c) copyright    2021-2026, Aregtech UG
 *                  Generated by Aregtech code generator tool.
 * Generated at     15.08.2021  12:23:44 GMT+02:00 
 ************************************************************************/

/************************************************************************
 * \file            pubservice/src/TrafficLightFSM.cpp
 * \ingroup         TrafficLight State Machine
 * \brief           This is an automatic generated code of TrafficLight 
 *                  State Machine class implementation.
 *                  Do not make changes in the file
 ************************************************************************/

/************************************************************************
 * Include files
 ************************************************************************/
#include "pubservice/src/TrafficLightFSM.hpp"

#include "pubservice/src/TrafficLightActionHandler.hpp"
#include "areg/component/DispatcherThread.hpp"
#include "areg/logging/GELog.h"

//////////////////////////////////////////////////////////////////////////
// use of namespace to access defined types directly
//////////////////////////////////////////////////////////////////////////
using namespace NETrafficLightFSM;


//////////////////////////////////////////////////////////////////////////
// Predefined local Macro
//////////////////////////////////////////////////////////////////////////

#define  INFO_PROCESSED(curr, next)         \
    LOG_DBG("FSM < %s >: The trigger < %s > was processed to switch from state < %s > ==> to state < %s >.", mFsmName.as_string(), nameTrigger, as_string(curr), as_string(next))

#define  INFO_PROCESSED_SAME(state)          \
    LOG_DBG("FSM < %s >: The trigger < %s > was processed in state < %s >.", mFsmName.as_string(), nameTrigger, as_string(state))

#define  INFO_NOT_PROCESSED                  \
    LOG_DBG("FSM < %s >: The trigger < %s > was not processed in state < %s >.", mFsmName.as_string(), nameTrigger, as_string(mState))

#define  INFO_ACTION_SWITCH(actionName)      \
    LOG_DBG("FSM < %s >: Processing action < %s > on trigger < %s >.", mFsmName.as_string(), (actionName), nameTrigger)

#define  INFO_ACTION_ENTER(actionName)       \
    LOG_DBG("FSM < %s >: Processing action < %s > entering state < %s >.", mFsmName.as_string(), (actionName), as_string(nextState))

#define  INFO_ACTION_EXIT(actionName)        \
    LOG_DBG("FSM < %s >: Processing action < %s > exiting state < %s >.", mFsmName.as_string(), (actionName), as_string(curState))

#define  INFO_ENTER_STATE(enterState)        \
    LOG_DBG("FSM < %s >: Entering state ==> < %s >.", mFsmName.as_string(), as_string(enterState))

#define  INFO_EXIT_STATE(exitState)          \
    LOG_DBG("FSM < %s >: Leaving state: < %s >.", mFsmName.as_string(), as_string(exitState))

#define  INFO_GO_STATE(fromState, toState)  \
     LOG_DBG("FSM < %s >: Switched state: < %s > ==> < %s >.", mFsmName.as_string(), as_string(fromState), as_string(toState))

#define  START_PROCESSING( triggerName )                        \
    bool    isProcessed = false;                                \
    const char* nameTrigger = triggerName;                      \
    if (startProcessing(nameTrigger) == true)                   \
    {                                                           \
        isProcessed = true;                                     \
        do                                                      \
        {


#define  END_PROCESSING( )                                      \
            isProcessed = false;                                \
            INFO_NOT_PROCESSED;                                 \
        } while (false);                                        \
      endProcessing();                                          \
    }                                                           \
    return isProcessed;                         

////////////////////////////////////////////////////////////////////////////////
// Log scope declaration 
////////////////////////////////////////////////////////////////////////////////
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_initFSM);
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_releaseFSM);
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_startProcessing);
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_enterState);
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_leaveState);

////////////////////////////////////////////////////////////////////////////////
// TrafficLightFSM::TrafficLightEventConsumer class implementation
////////////////////////////////////////////////////////////////////////////////

TrafficLightFSM::TrafficLightEventConsumer::TrafficLightEventConsumer( TrafficLightFSM & fsm )
    : NETrafficLightFSM::IEFsmEventConsumer ( )
    , mFsm  ( fsm )
{
}

/**
 * \brief   Called to process events
 **/
/* --------------------------------------------------------------------- */
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_TrafficLightEventConsumer_processEvent);
/* --------------------------------------------------------------------- */
void TrafficLightFSM::TrafficLightEventConsumer::processEvent( const NETrafficLightFSM::FsmEventData & data )
{
    LOG_SCOPE(generated_src_private_TrafficLightFSM_TrafficLightEventConsumer_processEvent);
    if ( mFsm.isOperable() )
    {
        LOG_DBG("Processing event < %s >.", NETrafficLightFSM::as_string(data.mData));
       
        switch ( data.mData )
        {
        case NETrafficLightFSM::FsmEventValue::EVENT_StartTrafficLight:
            mFsm.onEventStartTrafficLight();
            break;

        default:
            LOG_ERR("Unknown Event was requested to be processed!");
            ASSERT(false);
            break;   // do nothing
        }
    }
    else
    {
        LOG_WARN("Ignoring event < %s >, the state machine < %s > is not initialized.", NETrafficLightFSM::as_string(data.mData), mFsm.mFsmName.as_string());
    }
}

////////////////////////////////////////////////////////////////////////////////
// TrafficLightFSM::TimerConsumer class implementation 
////////////////////////////////////////////////////////////////////////////////

TrafficLightFSM::TrafficLightTimerConsumer::TrafficLightTimerConsumer( TrafficLightFSM & fsm )
    : TimerConsumer   ( )
    , mFsm              ( fsm )
{
}

/**
 * Called to process expired timers
 **/
/* --------------------------------------------------------------------- */
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_TrafficLightTimerConsumer_process_timer);
/* --------------------------------------------------------------------- */
void TrafficLightFSM::TrafficLightTimerConsumer::process_timer( Timer & timer )
{
    LOG_SCOPE(generated_src_private_TrafficLightFSM_TrafficLightTimerConsumer_process_timer);
    LOG_DBG("Processing Timer < %s >.", timer.name().as_string());
    
    do
    {
        if (timer.isStopped() == false)
        {
            if ( &timer == &mFsm.mTimerRed )
            {
                mFsm.onTimerRed( );
                break;
            }
            if ( &timer == &mFsm.mTimerYellowRed )
            {
                mFsm.onTimerYellowRed( );
                break;
            }
            if ( &timer == &mFsm.mTimerGreen )
            {
                mFsm.onTimerGreen( );
                break;
            }
            if ( &timer == &mFsm.mTimerYellowGreen )
            {
                mFsm.onTimerYellowGreen( );
                break;
            }
            if ( &timer == &mFsm.mTimerPedestrianWalk )
            {
                mFsm.onTimerPedestrianWalk( );
                break;
            }
            if ( &timer == &mFsm.mTimerVehicleWait )
            {
                mFsm.onTimerVehicleWait( );
                break;
            }

            LOG_ERR("Unknown timer was requested to be processed, none of existing timer has matched!");
            ASSERT(false);
        }
        else
        {
            LOG_WARN("The timer [ %s ] is already stopped, ignoring processing timer.", timer.name().as_string());
        }
        
    } while (false);
}

////////////////////////////////////////////////////////////////////////////////
// TrafficLightFSM predefined static members 
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
// TrafficLightFSM Class constructor / destructor 
////////////////////////////////////////////////////////////////////////////////
TrafficLightFSM::TrafficLightFSM( TrafficLightActionHandler & actionHandler, const std::string_view & instanceName /* = NETrafficLightFSM::InstanceDefaultName */ )
    : mActionHandler  ( actionHandler )
    
    , mTimerRed( static_cast< TimerConsumer &>(mTimerConsumer), "TrafficLightFsm::Red" )
    , mTimerYellowRed( static_cast< TimerConsumer &>(mTimerConsumer), "TrafficLightFsm::YellowRed" )
    , mTimerGreen( static_cast< TimerConsumer &>(mTimerConsumer), "TrafficLightFsm::Green" )
    , mTimerYellowGreen( static_cast< TimerConsumer &>(mTimerConsumer), "TrafficLightFsm::YellowGreen" )
    , mTimerPedestrianWalk( static_cast< TimerConsumer &>(mTimerConsumer), "TrafficLightFsm::PedestrianWalk" )
    , mTimerVehicleWait( static_cast< TimerConsumer &>(mTimerConsumer), "TrafficLightFsm::VehicleWait" )
    

    , mFsmName      ( String("TrafficLightFSM:") + instanceName )
    , mMasterThread ( nullptr )
    , mProcessing   ( false )
    , mState        ( TrafficLightFSM::FsmState::UNDEFINED )
    , mEventConsumer( self() )
    , mTimerConsumer( self() )
{
}

TrafficLightFSM::~TrafficLightFSM()
{
    NETrafficLightFSM::FsmEvent::removeListener( static_cast<NETrafficLightFSM::IEFsmEventConsumer &>(mEventConsumer) );
}

/**
 * Start processing trigger
 **/
inline bool TrafficLightFSM::startProcessing( const char* const triggerName )
{
    bool result = false;
    if (mState == TrafficLightFSM::FsmState::UNDEFINED)
    {
        LOG_SCOPE(generated_src_private_TrafficLightFSM_startProcessing);
        LOG_ERR("FSM < %s >: The State Machine is not initialized to call trigger < %s >!", mFsmName.as_string(), triggerName);
        ASSERT(false);
    }
    else if (mProcessing == true)
    {
        LOG_SCOPE(generated_src_private_TrafficLightFSM_startProcessing);
        LOG_ERR("FSM < %s >: Invalid trigger < %s > call during processing action!", mFsmName.as_string(), triggerName);
        ASSERT(false);
    }
    else
    {
        mProcessing = true;
        result      = true;
    }
    return result;
}

/**
 * End processing trigger
 **/
inline void TrafficLightFSM::endProcessing()
{
    mProcessing = false;
}

/**
 * Update state tree
 **/
inline void TrafficLightFSM::updateStateTree( const TrafficLightFSM::FsmState whichState, const TrafficLightFSM::FsmState curState )
{
    ASSERT(curState   != TrafficLightFSM::FsmState::STATE_SIZE);

    TrafficLightFSM::FsmState parent = sParrentStates[static_cast<int32_t>(whichState)];
    if (parent != TrafficLightFSM::FsmState::UNDEFINED)
    {
        updateStateTree(parent, curState);
    }

    mCurrentStates[static_cast<int32_t>(whichState)] = curState;
}

/**
 * Checks if the state is in parent tree
 **/
inline bool TrafficLightFSM::isInParentTree( TrafficLightFSM::FsmState whichState, const TrafficLightFSM::FsmState checkState )
{
    ASSERT(checkState != TrafficLightFSM::FsmState::UNDEFINED && checkState != TrafficLightFSM::FsmState::STATE_SIZE);

    bool result = whichState == checkState;
    if (result == false)
    {
        whichState  = sParrentStates[static_cast<int32_t>(whichState)];
        result      = whichState != TrafficLightFSM::FsmState::UNDEFINED ? isInParentTree(whichState, checkState) : false;
    }

    return result;
}

/**
 * Call to enter state and trigger actions on enter
 **/
inline void TrafficLightFSM::enterState( const TrafficLightFSM::FsmState curState, const TrafficLightFSM::FsmState nextState, const char* const nameTrigger )
{
    if (isInParentTree(curState, nextState) == false)
    {
        LOG_SCOPE(generated_src_private_TrafficLightFSM_enterState);
        INFO_ENTER_STATE(nextState);

        switch (nextState)
        {
        case TrafficLightFSM::FsmState::TRAFIC_LIGHT_OFF:
            INFO_ACTION_ENTER("actionPowerOff");
            mActionHandler.actionPowerOff();
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_ON:
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_INITIALIZE:
            INFO_ACTION_ENTER("actionPowerOn");
            mActionHandler.actionPowerOn();
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_FUNCTION:
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_YELLOW:
            INFO_ACTION_ENTER("actionVehicleYellow");
            mActionHandler.actionVehicleYellow();
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_RED:
            if (mTimerRed.isActive() == false)
            {
                LOG_DBG("Starting non active timer Red with 10000 ms of timeout and 1 numbers of repeats."); 
                mTimerRed.start_timer(10000, 1);
            }
            else
            {
                LOG_WARN("Ignoring start active timer Red with 10000 ms of timeout and 1 numbers of repeats."); 
            }
            INFO_ACTION_ENTER("actionVehicleRed");
            mActionHandler.actionVehicleRed();
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_VEHICLE_RED:
            if (mTimerVehicleWait.isActive() == false)
            {
                LOG_DBG("Starting non active timer VehicleWait with 1000 ms of timeout and 1 numbers of repeats."); 
                mTimerVehicleWait.start_timer(1000, 1);
            }
            else
            {
                LOG_WARN("Ignoring start active timer VehicleWait with 1000 ms of timeout and 1 numbers of repeats."); 
            }

            if (mTimerPedestrianWalk.isActive() == false)
            {
                LOG_DBG("Starting non active timer PedestrianWalk with 5000 ms of timeout and 1 numbers of repeats."); 
                mTimerPedestrianWalk.start_timer(5000, 1);
            }
            else
            {
                LOG_WARN("Ignoring start active timer PedestrianWalk with 5000 ms of timeout and 1 numbers of repeats."); 
            }

            INFO_ACTION_ENTER("actionPedestrianGreen");
            mActionHandler.actionPedestrianGreen(true);
            break;

        case TrafficLightFSM::FsmState::OPPOSIT_PEDESTRIAN_GREEN:
            INFO_ACTION_ENTER("actionVehicleGreen");
            mActionHandler.actionVehicleGreen(true);
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_GREEN:
            if (mTimerGreen.isActive() == false)
            {
                LOG_DBG("Starting non active timer Green with 10000 ms of timeout and 1 numbers of repeats."); 
                mTimerGreen.start_timer(10000, 1);
            }
            else
            {
                LOG_WARN("Ignoring start active timer Green with 10000 ms of timeout and 1 numbers of repeats."); 
            }
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_PEDESTRIAN_GREEN:
            if (mTimerVehicleWait.isActive() == false)
            {
                LOG_DBG("Starting non active timer VehicleWait with 1000 ms of timeout and 1 numbers of repeats."); 
                mTimerVehicleWait.start_timer(1000, 1);
            }
            else
            {
                LOG_WARN("Ignoring start active timer VehicleWait with 1000 ms of timeout and 1 numbers of repeats."); 
            }

            if (mTimerPedestrianWalk.isActive() == false)
            {
                LOG_DBG("Starting non active timer PedestrianWalk with 5000 ms of timeout and 1 numbers of repeats."); 
                mTimerPedestrianWalk.start_timer(5000, 1);
            }
            else
            {
                LOG_WARN("Ignoring start active timer PedestrianWalk with 5000 ms of timeout and 1 numbers of repeats."); 
            }

            INFO_ACTION_ENTER("actionPedestrianGreen");
            mActionHandler.actionPedestrianGreen(false);
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_VEHICLE_GREEN:
            INFO_ACTION_ENTER("actionVehicleGreen");
            mActionHandler.actionVehicleGreen(false);
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_START:
            sendEvent(NETrafficLightFSM::FsmEventValue::EVENT_StartTrafficLight);
            break;

        case TrafficLightFSM::FsmState::UNDEFINED:  // fall through
        case TrafficLightFSM::FsmState::STATE_SIZE: // fall through
        default:
            LOG_ERR("FSM < %s >: Unexpected State Machine State!", mFsmName.as_string());
            ASSERT(false);
        }

        TrafficLightFSM::FsmState child = sChildStates[static_cast<int32_t>(nextState)];
        if (child != TrafficLightFSM::FsmState::UNDEFINED)
        {
            enterState(curState, child, nameTrigger);
        }
        else
        {
            updateStateTree(curState,  TrafficLightFSM::FsmState::UNDEFINED);
            updateStateTree(nextState, nextState);

            INFO_GO_STATE(mState, nextState);

            mState = nextState;
        }
    }
}

/**
 * Call to exit state and trigger actions on exit
 **/
inline void TrafficLightFSM::leaveState( const TrafficLightFSM::FsmState curState, const TrafficLightFSM::FsmState nextState, const char* const nameTrigger )
{
    if (isInParentTree(curState, nextState) == false)
    {
        LOG_SCOPE(generated_src_private_TrafficLightFSM_leaveState);
        switch (curState)
        {
        case TrafficLightFSM::FsmState::TRAFIC_LIGHT_OFF:
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_ON:
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_INITIALIZE:
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_FUNCTION:
            LOG_DBG("Stopping timer Red, which current status is [ %s ].", mTimerRed.isActive() == true ? "ACTIVE" : "NOT ACTIVE");
            mTimerRed.stop_timer( );
            
            LOG_DBG("Stopping timer YellowRed, which current status is [ %s ].", mTimerYellowRed.isActive() == true ? "ACTIVE" : "NOT ACTIVE");
            mTimerYellowRed.stop_timer( );
            
            LOG_DBG("Stopping timer Green, which current status is [ %s ].", mTimerGreen.isActive() == true ? "ACTIVE" : "NOT ACTIVE");
            mTimerGreen.stop_timer( );

            LOG_DBG("Stopping timer YellowGreen, which current status is [ %s ].", mTimerYellowGreen.isActive() == true ? "ACTIVE" : "NOT ACTIVE");
            mTimerYellowGreen.stop_timer( );
            
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_YELLOW:
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_RED:
            LOG_DBG("Stopping timer PedestrianWalk, which current status is [ %s ].", mTimerPedestrianWalk.isActive() == true ? "ACTIVE" : "NOT ACTIVE");
            mTimerPedestrianWalk.stop_timer( );
            
            LOG_DBG("Stopping timer VehicleWait, which current status is [ %s ].", mTimerVehicleWait.isActive() == true ? "ACTIVE" : "NOT ACTIVE");
            mTimerVehicleWait.stop_timer( );
            
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_VEHICLE_RED:
            break;

        case TrafficLightFSM::FsmState::OPPOSIT_PEDESTRIAN_GREEN:
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_GREEN:
            LOG_DBG("Stopping timer PedestrianWalk, which current status is [ %s ].", mTimerPedestrianWalk.isActive() == true ? "ACTIVE" : "NOT ACTIVE");
            mTimerPedestrianWalk.stop_timer( );
            LOG_DBG("Stopping timer VehicleWait, which current status is [ %s ].", mTimerVehicleWait.isActive() == true ? "ACTIVE" : "NOT ACTIVE");
            mTimerVehicleWait.stop_timer( );
            INFO_ACTION_EXIT("actionPedestrianRed");
            mActionHandler.actionPedestrianRed();
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_PEDESTRIAN_GREEN:
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_VEHICLE_GREEN:
            break;

        case TrafficLightFSM::FsmState::TRAFFIC_LIGHT_START:
            break;

        case    TrafficLightFSM::FsmState::UNDEFINED:  // fall through
        case    TrafficLightFSM::FsmState::STATE_SIZE: // fall through
        default:
            LOG_ERR("FSM < %s >: Unexpected State Machine State!", mFsmName.as_string());
            ASSERT(false);
        }

        INFO_EXIT_STATE(curState);

        TrafficLightFSM::FsmState parent   = sParrentStates[static_cast<int32_t>(curState)];
        if (parent != TrafficLightFSM::FsmState::UNDEFINED && isInParentTree(nextState, parent) == false)
        {
            leaveState(parent, nextState, nameTrigger);
        }
    }
}

/**
 * Call to initialize State Machine. Initialize before calling any trigger.
 **/
void TrafficLightFSM::initFSM( DispatcherThread * ownerThread /*= nullptr*/ )
{
    LOG_SCOPE(generated_src_private_TrafficLightFSM_initFSM);
    if (mState != TrafficLightFSM::FsmState::UNDEFINED)
    {
        LOG_ERR("FSM < %s >: The initialization of state machine must be done on startup only!", mFsmName.as_string());
        ASSERT(false);
    }

    mMasterThread   = ownerThread != nullptr ? ownerThread : &(DispatcherThread::getCurrentDispatcherThread( ));
    NETrafficLightFSM::FsmEvent::addListener( static_cast<NETrafficLightFSM::IEFsmEventConsumer &>(mEventConsumer), *mMasterThread );
    
    mCurrentStates[static_cast<int32_t>(FsmState::UNDEFINED)] = TrafficLightFSM::FsmState::UNDEFINED;
   
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFIC_LIGHT_OFF)]          = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_ON)]          = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_INITIALIZE)]  = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_FUNCTION)]    = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_YELLOW)]      = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_RED)]         = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_VEHICLE_RED)] = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::OPPOSIT_PEDESTRIAN_GREEN)]  = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_GREEN)]       = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_PEDESTRIAN_GREEN)]  = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_VEHICLE_GREEN)]     = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_START)]       = TrafficLightFSM::FsmState::UNDEFINED;

    enterState(TrafficLightFSM::FsmState::UNDEFINED, TrafficLightFSM::FsmState::TRAFIC_LIGHT_OFF, "initFSM");
}

/**
 * Call to release State Machine. No trigger will be processed
 **/
void TrafficLightFSM::releaseFSM()
{
    LOG_SCOPE(generated_src_private_TrafficLightFSM_releaseFSM);
    LOG_DBG("Releasing < %s > State Machine. Initialize before calling triggers.", mFsmName.as_string());

    if ( mMasterThread != nullptr )
    {
        NETrafficLightFSM::FsmEvent::removeListener( static_cast<NETrafficLightFSM::IEFsmEventConsumer &>(mEventConsumer), *mMasterThread );
    }
    else
    {
        NETrafficLightFSM::FsmEvent::removeListener( static_cast<NETrafficLightFSM::IEFsmEventConsumer &>(mEventConsumer) );
    }

    mState          = TrafficLightFSM::FsmState::UNDEFINED;
    mMasterThread   = nullptr;

    mTimerRed.stop_timer( );
    mTimerYellowRed.stop_timer( );
    mTimerGreen.stop_timer( );
    mTimerYellowGreen.stop_timer( );
    mTimerPedestrianWalk.stop_timer( );
    mTimerVehicleWait.stop_timer( );

    mCurrentStates[static_cast<int32_t>(FsmState::UNDEFINED)] = TrafficLightFSM::FsmState::UNDEFINED;
   
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFIC_LIGHT_OFF)]          = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_ON)]          = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_INITIALIZE)]  = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_FUNCTION)]    = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_YELLOW)]      = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_RED)]         = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_VEHICLE_RED)] = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::OPPOSIT_PEDESTRIAN_GREEN)]  = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_GREEN)]       = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_PEDESTRIAN_GREEN)]  = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_VEHICLE_GREEN)]     = TrafficLightFSM::FsmState::UNDEFINED;
    mCurrentStates[static_cast<int32_t>(FsmState::TRAFFIC_LIGHT_START)]       = TrafficLightFSM::FsmState::UNDEFINED;
}


/**
 * Triggered to power off the traffic light.
 **/
/* --------------------------------------------------------------------- */
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_powerOff);
/* --------------------------------------------------------------------- */
bool TrafficLightFSM::powerOff()
{
    LOG_SCOPE(generated_src_private_TrafficLightFSM_powerOff);
    START_PROCESSING( "powerOff" );

    if ( isInParentTree(mState, TrafficLightFSM::FsmState::TRAFFIC_LIGHT_ON) == true )
    {
        TrafficLightFSM::FsmState next  = TrafficLightFSM::FsmState::TRAFIC_LIGHT_OFF;
        TrafficLightFSM::FsmState curr  = mState;
        leaveState(curr, next, nameTrigger);
        enterState(curr, next, nameTrigger);
        INFO_PROCESSED( curr, next );

        break;
    }

    END_PROCESSING( );
}

/**
 * Triggered to power on the traffic light.
 **/
/* --------------------------------------------------------------------- */
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_powerOn);
/* --------------------------------------------------------------------- */
bool TrafficLightFSM::powerOn()
{
    LOG_SCOPE(generated_src_private_TrafficLightFSM_powerOn);
    START_PROCESSING( "powerOn" );

    if ( mState == TrafficLightFSM::FsmState::TRAFIC_LIGHT_OFF )
    {
        TrafficLightFSM::FsmState next  = TrafficLightFSM::FsmState::TRAFFIC_LIGHT_ON;
        TrafficLightFSM::FsmState curr  = mState;
        leaveState(curr, next, nameTrigger);
        enterState(curr, next, nameTrigger);  
        INFO_PROCESSED( curr, next );

        break;
    }

    END_PROCESSING( );
}

/**
 * Triggered to start controlling the traffic light.
 **/
/* --------------------------------------------------------------------- */
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_startTrafficControl);
/* --------------------------------------------------------------------- */
bool TrafficLightFSM::startTrafficControl()
{
    LOG_SCOPE(generated_src_private_TrafficLightFSM_startTrafficControl);
    START_PROCESSING( "startTrafficControl" );

    if ( mState == TrafficLightFSM::FsmState::TRAFFIC_LIGHT_INITIALIZE )
    {
        TrafficLightFSM::FsmState next  = TrafficLightFSM::FsmState::TRAFFIC_LIGHT_FUNCTION;
        TrafficLightFSM::FsmState curr  = mState;
        leaveState(curr, next, nameTrigger);

        if (mTimerYellowGreen.isActive() == false)
        {
            LOG_DBG("Starting non active timer YellowGreen with 3000 ms of timeout and 1 numbers of repeats."); 
            mTimerYellowGreen.start_timer(3000, 1);
        }
        else
        {
            LOG_WARN("Ignoring start active timer YellowGreen with 3000 ms of timeout and 1 numbers of repeats."); 
        }

        enterState(curr, next, nameTrigger);  
        INFO_PROCESSED( curr, next );

        break;
    }

    END_PROCESSING( );
}

/**
 * Triggered to stop the traffic light controller.
 **/
/* --------------------------------------------------------------------- */
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_stopTrafficControl);
/* --------------------------------------------------------------------- */
bool TrafficLightFSM::stopTrafficControl()
{
    LOG_SCOPE(generated_src_private_TrafficLightFSM_stopTrafficControl);
    START_PROCESSING( "stopTrafficControl" );

    if ( isInParentTree(mState, TrafficLightFSM::FsmState::TRAFFIC_LIGHT_FUNCTION) == true )
    {
        TrafficLightFSM::FsmState next  = TrafficLightFSM::FsmState::TRAFFIC_LIGHT_INITIALIZE;
        TrafficLightFSM::FsmState curr  = mState;
        leaveState(curr, next, nameTrigger);
        enterState(curr, next, nameTrigger);  
        INFO_PROCESSED( curr, next );

        break;
    }

    END_PROCESSING( );
}


/**
 * Triggered on event 'StartTrafficLight'
 **/
/* --------------------------------------------------------------------- */
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_onEventStartTrafficLight);
/* --------------------------------------------------------------------- */
bool TrafficLightFSM::onEventStartTrafficLight()
{
    LOG_SCOPE(generated_src_private_TrafficLightFSM_onEventStartTrafficLight);
    START_PROCESSING("Event_StartTrafficLight");

    if ( mState == TrafficLightFSM::FsmState::TRAFFIC_LIGHT_START )
    {
        TrafficLightFSM::FsmState next  = TrafficLightFSM::FsmState::TRAFFIC_LIGHT_YELLOW;
        TrafficLightFSM::FsmState curr  = mState;
        leaveState(curr, next, nameTrigger);
        enterState(curr, next, nameTrigger);  
        INFO_PROCESSED(curr, next);

        break;
    }

    END_PROCESSING();
}

/**
 * Triggered on timer 'Red'
 **/
/* --------------------------------------------------------------------- */
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_onTimerRed);
/* --------------------------------------------------------------------- */
bool TrafficLightFSM::onTimerRed()
{
    LOG_SCOPE(generated_src_private_TrafficLightFSM_onTimerRed);
    START_PROCESSING("Timer_Red");

    if (isInParentTree(mState, TrafficLightFSM::FsmState::TRAFFIC_LIGHT_RED))
    {
        TrafficLightFSM::FsmState next  = TrafficLightFSM::FsmState::TRAFFIC_LIGHT_YELLOW;
        TrafficLightFSM::FsmState curr  = mState;
        leaveState(curr, next, nameTrigger);

        if (mTimerYellowGreen.isActive() == false)
        {
            LOG_DBG("Starting non active timer YellowGreen with 3000 ms of timeout and 1 numbers of repeats."); 
            mTimerYellowGreen.start_timer(3000, 1);
        }
        else
        {
            LOG_WARN("Ignoring start active timer YellowGreen with 3000 ms of timeout and 1 numbers of repeats."); 
        }

        enterState(curr, next, nameTrigger);  
        INFO_PROCESSED(curr, next);

        break;
    }

    END_PROCESSING();
}

/**
 * Triggered on timer 'YellowRed'
 **/
/* --------------------------------------------------------------------- */
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_onTimerYellowRed);
/* --------------------------------------------------------------------- */
bool TrafficLightFSM::onTimerYellowRed()
{
    LOG_SCOPE(generated_src_private_TrafficLightFSM_onTimerYellowRed);
    START_PROCESSING("Timer_YellowRed");

    if ( mState == TrafficLightFSM::FsmState::TRAFFIC_LIGHT_YELLOW )
    {
        TrafficLightFSM::FsmState next  = TrafficLightFSM::FsmState::TRAFFIC_LIGHT_RED;
        TrafficLightFSM::FsmState curr  = mState;
        leaveState(curr, next, nameTrigger);
        enterState(curr, next, nameTrigger);  
        INFO_PROCESSED(curr, next);

        break;
    }

    END_PROCESSING();
}

/**
 * Triggered on timer 'Green'
 **/
/* --------------------------------------------------------------------- */
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_onTimerGreen);
/* --------------------------------------------------------------------- */
bool TrafficLightFSM::onTimerGreen()
{
    LOG_SCOPE(generated_src_private_TrafficLightFSM_onTimerGreen);
    START_PROCESSING("Timer_Green");

    if (isInParentTree(mState, TrafficLightFSM::FsmState::TRAFFIC_LIGHT_GREEN) == true)
    {
        TrafficLightFSM::FsmState next  = TrafficLightFSM::FsmState::TRAFFIC_LIGHT_YELLOW;
        TrafficLightFSM::FsmState curr  = mState;
        leaveState(curr, next, nameTrigger);
            if (mTimerYellowRed.isActive() == false)
            {
                LOG_DBG("Starting non active timer YellowRed with 3000 ms of timeout and 1 numbers of repeats."); 
                mTimerYellowRed.start_timer(3000, 1);
            }
            else
            {
                LOG_WARN("Ignoring start active timer YellowRed with 3000 ms of timeout and 1 numbers of repeats."); 
            }
        enterState(curr, next, nameTrigger);  
        INFO_PROCESSED(curr, next);

        break;
    }

    END_PROCESSING();
}

/**
 * Triggered on timer 'YellowGreen'
 **/
/* --------------------------------------------------------------------- */
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_onTimerYellowGreen);
/* --------------------------------------------------------------------- */
bool TrafficLightFSM::onTimerYellowGreen()
{
    LOG_SCOPE(generated_src_private_TrafficLightFSM_onTimerYellowGreen);
    START_PROCESSING("Timer_YellowGreen");

    if ( mState == TrafficLightFSM::FsmState::TRAFFIC_LIGHT_YELLOW )
    {
        TrafficLightFSM::FsmState next  = TrafficLightFSM::FsmState::TRAFFIC_LIGHT_GREEN;
        TrafficLightFSM::FsmState curr  = mState;
        leaveState(curr, next, nameTrigger);
        enterState(curr, next, nameTrigger);  
        INFO_PROCESSED(curr, next);

        break;
    }

    END_PROCESSING();
}

/**
 * Triggered on timer 'PedestrianWalk'
 **/
/* --------------------------------------------------------------------- */
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_onTimerPedestrianWalk);
/* --------------------------------------------------------------------- */
bool TrafficLightFSM::onTimerPedestrianWalk()
{
    LOG_SCOPE(generated_src_private_TrafficLightFSM_onTimerPedestrianWalk);
    START_PROCESSING("Timer_PedestrianWalk");

    if (isInParentTree(mState, TrafficLightFSM::FsmState::TRAFFIC_LIGHT_GREEN) == true)
    {
        INFO_ACTION_SWITCH("actionPedestrianRed");
        mActionHandler.actionPedestrianRed();
        INFO_PROCESSED_SAME(mState);

        break;
    }

    if (isInParentTree(mState, TrafficLightFSM::FsmState::TRAFFIC_LIGHT_RED) == true)
    {
        INFO_ACTION_SWITCH("actionPedestrianRed");
        mActionHandler.actionPedestrianRed();
        INFO_PROCESSED_SAME(mState);

        break;
    }

    END_PROCESSING();
}

/**
 * Triggered on timer 'VehicleWait'
 **/
/* --------------------------------------------------------------------- */
DEF_LOG_SCOPE(generated_src_private_TrafficLightFSM_onTimerVehicleWait);
/* --------------------------------------------------------------------- */
bool TrafficLightFSM::onTimerVehicleWait()
{
    LOG_SCOPE(generated_src_private_TrafficLightFSM_onTimerVehicleWait);
    START_PROCESSING("Timer_VehicleWait");

    if ( mState == TrafficLightFSM::FsmState::TRAFFIC_LIGHT_VEHICLE_RED )
    {
        TrafficLightFSM::FsmState next  = TrafficLightFSM::FsmState::OPPOSIT_PEDESTRIAN_GREEN;
        TrafficLightFSM::FsmState curr  = mState;
        leaveState(curr, next, nameTrigger);
        enterState(curr, next, nameTrigger);  
        INFO_PROCESSED(curr, next);

        break;
    }

    if ( mState == TrafficLightFSM::FsmState::TRAFFIC_PEDESTRIAN_GREEN )
    {
        TrafficLightFSM::FsmState next  = TrafficLightFSM::FsmState::TRAFFIC_VEHICLE_GREEN;
        TrafficLightFSM::FsmState curr  = mState;
        leaveState(curr, next, nameTrigger);
        enterState(curr, next, nameTrigger);  
        INFO_PROCESSED(curr, next);

        break;
    }

    END_PROCESSING();
}

////////////////////////////////////////////////////////////////////////////////
// End generate TrafficLightFSM.cpp file
////////////////////////////////////////////////////////////////////////////////
