
//////////////////////////////////////////////////////////////////////////
// Begin generate TrafficLightActionHandler.hpp file
//////////////////////////////////////////////////////////////////////////

#pragma once

/************************************************************************
 * (c) copyright    2021-2026, Aregtech UG
 *                  Generated by Aregtech code generator tool.
 * Generated at     16.08.2021  12:45:39 GMT+02:00 
 ************************************************************************/

/************************************************************************
 * \file            pubservice/src/TrafficLightActionHandler.hpp
 * \ingroup         TrafficLight State Machine
 * \brief           This is an automatic generated code of TrafficLight action handler.
 ************************************************************************/

/************************************************************************
 * Include files
 ************************************************************************/

#include "pubservice/src/TrafficLightDefs.hpp"

//////////////////////////////////////////////////////////////////////////
// TrafficLightActionHandler class declaration 
//////////////////////////////////////////////////////////////////////////
/**
 * \brief   TrafficLightActionHandler action handler interface.
 *          In this classes are declared all action methods of
 *          TrafficLight State Machine.
 *          To implement State Machine, inherit this class, implement
 *          all action methods. The action handler is triggered from
 *          TrafficLight State Machine on state change or on trigger call.
 **/
class TrafficLightActionHandler
{

//////////////////////////////////////////////////////////////////////////
// Constructor / Destructor
//////////////////////////////////////////////////////////////////////////
protected:

   /**
    * \brief   TrafficLightActionHandler constructor is hidden from direct call
    **/
   TrafficLightActionHandler() = default;

   /**
    * \brief   TrafficLightActionHandler destructor
    **/
   virtual ~TrafficLightActionHandler() = default;
   

//////////////////////////////////////////////////////////////////////////
// TrafficLight actions
//////////////////////////////////////////////////////////////////////////
public:
/************************************************************************/
// TrafficLightActionHandler action overrides
/************************************************************************/

   /**
    * \brief   Action to perform when traffic light is off.
    **/
   virtual void actionPowerOff() = 0;

   /**
    * \brief   Acton to perform when power on the traffic light.
    **/
   virtual void actionPowerOn() = 0;

   /**
    * \brief   Action to perform when vehicle light is yellow.
    **/
   virtual void actionVehicleYellow() = 0;

   /**
    * \brief   Action to perform when vehicle light is red.
    **/
   virtual void actionVehicleRed() = 0;

   /**
    * \brief   Action to perform when pedestrian light is red.
    **/
   virtual void actionPedestrianRed() = 0;

   /**
    * \brief   Action to perform when vehicle light is green.
    * \param   isEastWest    Flag, indicating whether this action is triggered for East-West or South-North direction. The default direction is South-North.
    **/
   virtual void actionVehicleGreen( bool isEastWest ) = 0;

   /**
    * \brief   Action to perform when pedestrian light state is green.
    * \param   isEastWest    Flag, indicating whether this action is triggered for East-West or South-North direction. The default direction is South-North.
    **/
   virtual void actionPedestrianGreen( bool isEastWest ) = 0;

//////////////////////////////////////////////////////////////////////////
// Forbidden calls.
//////////////////////////////////////////////////////////////////////////
private:
    AREG_NOCOPY_NOMOVE( TrafficLightActionHandler );
};

//////////////////////////////////////////////////////////////////////////
// End generate TrafficLightActionHandler.hpp file
//////////////////////////////////////////////////////////////////////////
