/************************************************************************
 * (c) copyright    2021-2026, Aregtech (Artak Avetyan)
 *                  Generated by Aregtech code generator tool.
 * Generated at     03.01.2022  12:45:39 GMT+02:00 
 ************************************************************************/

/************************************************************************
 * \file			pubservice/src/TrafficLightDefs.cpp
 * \ingroup         TrafficLight State Machine
 * \brief      		This is an automatic generated code of TrafficLight namespace.
 ************************************************************************/

/************************************************************************
 * Include files
 ************************************************************************/
#include "pubservice/src/TrafficLightDefs.hpp"

//////////////////////////////////////////////////////////////////////////
// NETrafficLightFSM Namespace implementation
//////////////////////////////////////////////////////////////////////////
