
#pragma once

/************************************************************************
 * (c) copyright    2021-2026, Aregtech UG
 *                  Generated by Aregtech code generator tool.
 * Generated at     03.01.2022  12:45:39 GMT+02:00 
 ************************************************************************/

/************************************************************************
 * \file            pubservice/src/TrafficLightDefs.hpp
 * \ingroup         TrafficLight State Machine
 * \brief           This is an automatic generated code of TrafficLight namespace.
 ************************************************************************/

/************************************************************************
 * Include files
 ************************************************************************/

#include "areg/component/EventTemplate.hpp"
#include <string_view>

//////////////////////////////////////////////////////////////////////////
// NETrafficLightFSM Namespace Declaration 
//////////////////////////////////////////////////////////////////////////
/**
 * \brief   NETrafficLightFSM namespace is used to declare
 *          predefined Constants, Types, Structures, Events and Timers
 *          of TrafficLight State Machine.
 **/
namespace NETrafficLightFSM
{

//////////////////////////////////////////////////////////////////////////
// Predefined constants of TrafficLight State Machine
//////////////////////////////////////////////////////////////////////////
    /**
     * \brief   NETrafficLightFSM::InstanceDefaultName
     *          The default name of TrafficLight State Machine instance.
     **/
    constexpr std::string_view   InstanceDefaultName{ "TrafficLight" };
    
//////////////////////////////////////////////////////////////////////////
// Available predefined events of TrafficLight State Machine
//////////////////////////////////////////////////////////////////////////
    /**
     * \brief   NETrafficLightFSM::eFsmEventValue
     *          TrafficLight State Machine available Event IDs
     **/
    enum class eFsmEventData
    {
        EVENT_StartTrafficLight /** DESCRIPTION MISSED **/

    };
   
    /**
     * \brief   Returns human readable string of NETrafficLightFSM::eFsmEventValue event values
     **/
    inline const char* getString( const NETrafficLightFSM::eFsmEventData value );

    //////////////////////////////////////////////////////////////////////////
    // NETrafficLightFSM::FsmEventData class declaration
    //////////////////////////////////////////////////////////////////////////
    /************************************************************************
     * \brief   This is predefined Event Data class containing Event ID.
     *          When Event is triggered in State Machine, depending on
     *          Event ID, the appropriate processing method will be fired.
     ************************************************************************/
    class FsmEventData
    {
    //////////////////////////////////////////////////////////////////////////
    // Constructors / Destructor
    //////////////////////////////////////////////////////////////////////////
    public:
        FsmEventData( const NETrafficLightFSM::eFsmEventData & data )
            : mData ( data )
        {
        }

        FsmEventData( const FsmEventData & data ) = default;
        ~FsmEventData() = default;
   
    public:
        /**
         * \brief   Returns event data value.
         **/
        inline const NETrafficLightFSM::eFsmEventData & getData() const
        {
            return mData;
        }

    //////////////////////////////////////////////////////////////////////////
    // Member variable
    //////////////////////////////////////////////////////////////////////////
    public:
        /**
         * \brief   The Event Data
         **/
        const NETrafficLightFSM::eFsmEventData  mData;

    //////////////////////////////////////////////////////////////////////////
    // Hidden / Forbidden methods
    //////////////////////////////////////////////////////////////////////////
    private:
        FsmEventData() = delete;
        NETrafficLightFSM::FsmEventData & operator = ( const NETrafficLightFSM::FsmEventData & src ) = delete;
   };
   
//////////////////////////////////////////////////////////////////////////
// Declare FSM Event and Event Consumer classes
//////////////////////////////////////////////////////////////////////////
/**
 * \brief   Declaration of NETrafficLightFSM::FsmEvent of internal type
 *          and declaration of NETrafficLightFSM::IEFsmEventConsumer, which
 *          will be registered in the same thread, where it is instantiated.
 **/
AREG_DECLARE_INTERNAL_EVENT(FsmEventData, FsmEvent, IEFsmEventConsumer);

//////////////////////////////////////////////////////////////////////////
// Available predefined Timers of TrafficLight State Machine
//////////////////////////////////////////////////////////////////////////

    /**
     * \brief   NETrafficLightFSM::FsmTimer
                TrafficLight State Machine available Timer IDs
     *          
     **/
    enum class FsmTimer
    {
        Red            /** DESCRIPTION MISSED **/
      , YellowRed      /** DESCRIPTION MISSED **/
      , Green          /** DESCRIPTION MISSED **/
      , YellowGreen    /** DESCRIPTION MISSED **/
      , PedestrianWalk /** DESCRIPTION MISSED **/
      , VehicleWait    /** DESCRIPTION MISSED **/   
    };
   
    /**
     * \brief   Returns human readable string of NETrafficLightFSM::FsmTimer timer values
     **/
    inline const char* getString( const NETrafficLightFSM::FsmTimer value );

};

//////////////////////////////////////////////////////////////////////////
// NETrafficLightFSM namespace inline methods
//////////////////////////////////////////////////////////////////////////
/**
 * Returns human readable string of event data
 **/
inline const char * NETrafficLightFSM::getString( const NETrafficLightFSM::eFsmEventData value )
{
    switch ( value )
    {
    case NETrafficLightFSM::eFsmEventData::EVENT_StartTrafficLight:
        return "NETrafficLightFSM::eFsmEventData::EVENT_StartTrafficLight";
    default:
        return "ERR: Unexpected NETrafficLightFSM::eFsmEventData event value!";
    }
}

/**
 * Returns human readable string of timers
 **/
inline const char * NETrafficLightFSM::getString( const NETrafficLightFSM::FsmTimer value )
{
    switch ( value )
    {
    case NETrafficLightFSM::FsmTimer::Red:
        return "NETrafficLightFSM::FsmTimer::Red";
    case NETrafficLightFSM::FsmTimer::YellowRed:
        return "NETrafficLightFSM::FsmTimer::YellowRed";
    case NETrafficLightFSM::FsmTimer::Green:
        return "NETrafficLightFSM::FsmTimer::Green";
    case NETrafficLightFSM::FsmTimer::YellowGreen:
        return "NETrafficLightFSM::FsmTimer::YellowGreen";
    case NETrafficLightFSM::FsmTimer::PedestrianWalk:
        return "NETrafficLightFSM::FsmTimer::PedestrianWalk";
    case NETrafficLightFSM::FsmTimer::VehicleWait:
        return "NETrafficLightFSM::FsmTimer::VehicleWait";
    default:
        return "ERR: Unexpected NETrafficLightFSM::FsmTimer timer value!";
    }
}
