
//////////////////////////////////////////////////////////////////////////
// Begin generate TrafficLightActionHandler.cpp file
//////////////////////////////////////////////////////////////////////////

/************************************************************************
 * (c) copyright    2021-2026, Aregtech (Artak Avetyan)
 *                  Generated by Aregtech code generator tool.
 * Generated at     16.08.2021  12:45:39 GMT+02:00 
 ************************************************************************/

/************************************************************************
 * \file            pubservice/src/TrafficLightActionHandler.cpp
 * \ingroup         TrafficLight State Machine
 * \brief           This is an automatic generated code of TrafficLight action handler.
 ************************************************************************/

/************************************************************************
 * Include files
 ************************************************************************/

#include "pubservice/src/TrafficLightActionHandler.hpp"

//////////////////////////////////////////////////////////////////////////
// End generate TrafficLightActionHandler.cpp file
//////////////////////////////////////////////////////////////////////////
