
//////////////////////////////////////////////////////////////////////////
// Begin generate TrafficLightFSM.hpp file
//////////////////////////////////////////////////////////////////////////

#pragma once

/************************************************************************
 * (c) copyright    2021-2026
 *                  Generated by Aregtech code generator tool.
 * Generated at     03.01.2022  12:23:44 GMT+02:00 
 ************************************************************************/

/**
 * \file       	    pubservice/src/TrafficLightFSM.hpp
 * \ingroup         TrafficLight State Machine
 * \brief      	    This is an automatic generated code of TrafficLight 
 *                  State Machine class declaration.
 *                  Do not make changes in the file.
 *
 *                  NOTE:   This class is generated as thread unsafe. 
 *                          No locking mechanism accessing methods or variables is provided.
 *
 **/

/************************************************************************
 * Include files
 ************************************************************************/
#include "pubservice/src/TrafficLightDefs.hpp"

#include "areg/base/String.hpp"
#include "areg/component/Timer.hpp"
#include "areg/component/TimerConsumer.hpp"

/************************************************************************
 * Dependencies
 ************************************************************************/
class TrafficLightActionHandler;
namespace areg { class DispatcherThread; }

//////////////////////////////////////////////////////////////////////////
// TrafficLightFSM class declaration 
//////////////////////////////////////////////////////////////////////////
/**
 * \brief   TrafficLightFSM is a generated State Machine class.
 *          Instantiate by passing reference of action handler.
 *          The actions will be triggered depending on states.
 **/
class TrafficLightFSM
{
//////////////////////////////////////////////////////////////////////////
// Internal classes
//////////////////////////////////////////////////////////////////////////
private:
//////////////////////////////////////////////////////////////////////////
// TrafficLightFSM::TrafficLightEventConsumer class declaration
//////////////////////////////////////////////////////////////////////////
    friend class TrafficLightEventConsumer;

    /**
     * \brief   TrafficLight state-machine event consumer to dispatch the events. 
     **/
    class TrafficLightEventConsumer : public NETrafficLightFSM::IEFsmEventConsumer
    {
    public:
        /**
         * \brief   Constructs and initializes TrafficLight Event Consumer object.
         * \param   fsm     The instance of state-machine.
         **/
        TrafficLightEventConsumer( TrafficLightFSM & fsm );

        virtual ~TrafficLightEventConsumer() = default;

    private:
    /************************************************************************/
    // Event Consumer override
    /************************************************************************/
        /**
         * \brief   Process State Machine events.
         * \param   data    The Event Data object passed to event when fired.
         * \remark  The method is not thread safe.
         **/
        void processEvent( const NETrafficLightFSM::FsmEventData & data ) override;

    private:
    /************************************************************************/
    // Hidden member variables
    /************************************************************************/
        /**
         * \brief   The instance of TrafficLight state-mashine. 
         **/
        TrafficLightFSM &   mFsm;

    private:
    /************************************************************************/
    // Forbidden calls
    /************************************************************************/
        TrafficLightEventConsumer() = delete;
        AREG_NOCOPY_NOMOVE( TrafficLightEventConsumer );
    };

private:
//////////////////////////////////////////////////////////////////////////
// TrafficLightFSM::TrafficLightTimerConsumer class declaration
//////////////////////////////////////////////////////////////////////////
    friend class TrafficLightTimerConsumer;

    /**
     * \brief   TrafficLight state-machine timer consumer to dispatch the timer events. 
     **/
    class TrafficLightTimerConsumer : public areg::TimerConsumer
    {
    public:
        /**
         * \brief   Constructs and initializes TrafficLight Timer Consumer object.
         * \param   fsm     The instance of state-machine.
         **/
        TrafficLightTimerConsumer( TrafficLightFSM & fsm );

        virtual ~TrafficLightTimerConsumer() = default;

    /************************************************************************/
    // Timer Consumer override
    /************************************************************************/
    private:
        /**
         * \brief   Process State Machine timers.
         **/
        void processTimer( areg::Timer & timer ) override;
    
    private:
    /************************************************************************/
    // Hidden member variables
    /************************************************************************/
        /**
         * \brief   The instance of TrafficLight state-mashine. 
         **/
        TrafficLightFSM &   mFsm;

    private:
    /************************************************************************/
    // Forbidden calls
    /************************************************************************/
        TrafficLightTimerConsumer() = delete;
        AREG_NOCOPY_NOMOVE( TrafficLightTimerConsumer );
    };

//////////////////////////////////////////////////////////////////////////
// Predefined constants and types
//////////////////////////////////////////////////////////////////////////
private:
    /************************************************************************
     * \brief   TrafficLightFSM::FsmState
     *          The predefined states of TrafficLight State Machine.
     ************************************************************************/
    enum class FsmState
    {
          UNDEFINED

        , TRAFIC_LIGHT_OFF
        , TRAFFIC_LIGHT_ON
        , TRAFFIC_LIGHT_INITIALIZE
        , TRAFFIC_LIGHT_FUNCTION
        , TRAFFIC_LIGHT_YELLOW
        , TRAFFIC_LIGHT_RED
        , TRAFFIC_LIGHT_VEHICLE_RED
        , OPPOSIT_PEDESTRIAN_GREEN
        , TRAFFIC_LIGHT_GREEN
        , TRAFFIC_PEDESTRIAN_GREEN
        , TRAFFIC_VEHICLE_GREEN
        , TRAFFIC_LIGHT_START
   
        , STATE_SIZE
   };
   
    /**
     * \brief   Returns the string value of TrafficLight states.
     * \param   state   The state value of TrafficLight State Machine.
     **/
    static inline const char* getString( const TrafficLightFSM::FsmState state );
    
//////////////////////////////////////////////////////////////////////////
// Constructor / Destructor
//////////////////////////////////////////////////////////////////////////
public:
    /**
     * \brief   Instantiates and initializes FSM internals
     * \param   actionHandler   The reference of action handler object to trigger actions.
     * \param   instanceName    The name of FSM instance. By default it has the name of FSM. 
     **/
    TrafficLightFSM( TrafficLightActionHandler & actionHandler, const std::string_view & instanceName = NETrafficLightFSM::InstanceDefaultName );

    /**
     * \brief   TrafficLightFSM class destructor
     **/
    ~TrafficLightFSM();

private:
    /**
     * \brief   Reference to State Machine action handler class object
     **/
    TrafficLightActionHandler& mActionHandler;

public:

    /**
     * \brief   Initialize State Machine. Call before calling any trigger.
     * \param   ownerThread The pointer of master thread to process internal events and timers.
     **/
    void initFSM( areg::DispatcherThread * ownerThread = nullptr );

    /**
     * \brief   Release State Machine. Call when complete working with FSM.
     **/
    void releaseFSM();

    /**
     * \brief   Call to send and event.
     * \param   data    The name of event, generated in NETrafficLightFSM namespace.
     **/
    inline void sendEvent( const NETrafficLightFSM::FsmEventValue data );

//////////////////////////////////////////////////////////////////////////
// TrafficLight State Machine Triggers
//////////////////////////////////////////////////////////////////////////
public:

    /**
     * \brief   Triggered to power off the traffic light.
     *
     * \return  Returns true if trigger was processed in the current state, otherwise it returns false.
     * \remark  The method is not thread safe.
     **/
    bool powerOff();

    /**
     * \brief   Triggered to power on the traffic light.
     *
     * \return  Returns true if trigger was processed in the current state, otherwise it returns false.
     * \remark  The method is not thread safe.
     **/
    bool powerOn();

    /**
     * \brief   Triggered to start controlling the traffic light.
     *
     * \return  Returns true if trigger was processed in the current state, otherwise it returns false.
     * \remark  The method is not thread safe.
     **/
    bool startTrafficControl();

    /**
     * \brief   Triggered to stop the traffic light controller.
     *
     * \return  Returns true if trigger was processed in the current state, otherwise it returns false.
     * \remark  The method is not thread safe.
     **/
    bool stopTrafficControl();

//////////////////////////////////////////////////////////////////////////
// Get / Set attributes
//////////////////////////////////////////////////////////////////////////
public:

//////////////////////////////////////////////////////////////////////////
// Timer functions
//////////////////////////////////////////////////////////////////////////
public:
/************************************************************************/
// Timer attributes
/************************************************************************/

    /**
     * \brief   Returns true if specified timer object is active
     **/
     inline bool isTimerActive( const NETrafficLightFSM::FsmTimer whichTimer ) const;

private:
/************************************************************************/
// Timer Triggers
/************************************************************************/

    /**
     * \brief   Timer Red object
     **/
    areg::Timer     mTimerRed;
    /**
     * \brief   Timer Red trigger
     * \return  Returns true if timer was processed in the current state. Otherwise it returns false.
     **/
    bool onTimerRed();
    
    /**
     * \brief   Timer YellowRed object
     **/
    areg::Timer     mTimerYellowRed;
    /**
     * \brief   Timer YellowRed trigger
     * \return  Returns true if timer was processed in the current state. Otherwise it returns false.
     **/
    bool onTimerYellowRed();
    
    /**
     * \brief   Timer Green object
     **/
    areg::Timer     mTimerGreen;
    /**
     * \brief   Timer Green trigger
     * \return  Returns true if timer was processed in the current state. Otherwise it returns false.
     **/
    bool onTimerGreen();
    
    /**
     * \brief   Timer YellowGreen object
     **/
    areg::Timer     mTimerYellowGreen;
    /**
     * \brief   Timer YellowGreen trigger
     * \return  Returns true if timer was processed in the current state. Otherwise it returns false.
     **/
    bool onTimerYellowGreen();
    
    /**
     * \brief   Timer PedestrianWalk object
     **/
    areg::Timer     mTimerPedestrianWalk;
    /**
     * \brief   Timer PedestrianWalk trigger
     * \return  Returns true if timer was processed in the current state. Otherwise it returns false.
     **/
    bool onTimerPedestrianWalk();
    
    /**
     * \brief   Timer VehicleWait object
     **/
    areg::Timer     mTimerVehicleWait;
    /**
     * \brief   Timer VehicleWait trigger
     * \return  Returns true if timer was processed in the current state. Otherwise it returns false.
     **/
    bool onTimerVehicleWait();
    
private:
/************************************************************************/
// Event Triggers
/************************************************************************/

    /**
     * \brief   Event StartTrafficLight trigger
     * \return  Returns true if event was processed in the current state. Otherwise it returns false.
     **/
    bool onEventStartTrafficLight();

//////////////////////////////////////////////////////////////////////////
// Hidden internal processing methods and attributes
//////////////////////////////////////////////////////////////////////////
private:
    /**
     * \brief   Returns true if trigger can start processing. If a trigger called from processing action, this will return false.
     * \param   triggerName The string name of trigger to process
     **/
    bool startProcessing( const char* const triggerName );

    /**
     * \brief   Called when complete processing trigger
     **/
    void endProcessing();

    /**
     * \brief   Called when entering next state
     * \param   curState    Value of current state
     * \param   nextState   Value of next state to enter
     * \param   nameTrigger The string name of currently processing trigger
     **/
    void enterState( const TrafficLightFSM::FsmState curState, const TrafficLightFSM::FsmState nextState, const char* const nameTrigger );

    /**
     * \brief   Called when leaving current state
     * \param   curState    Value of current state
     * \param   nextState   Value of next state to enter
     * \param   nameTrigger The string name of currently processing trigger
     **/
    void leaveState( const TrafficLightFSM::FsmState curState, const TrafficLightFSM::FsmState nextState, const char* const nameTrigger );

    /**
     * \brief   Called when updating state tree
     * \param   whichState  The value of state to update, including child states
     * \param   curState    The value of current state
     **/
    void updateStateTree( const TrafficLightFSM::FsmState whichState, const TrafficLightFSM::FsmState curState );

    /**
     * \brief   Returns true if specified state is in parent tree, e.g. if current state is in child sub-state tree.
     * \param   whichState  The state for checking, usually current state.
     * \param   checkState  The state to check.
     **/
    bool isInParentTree( TrafficLightFSM::FsmState whichState, const TrafficLightFSM::FsmState checkState );

    /**
     * \brief   Returns true if state machine is in operable state, i.e. it is not UNDEFINED
     **/
    inline bool isOperable() const;

    /**
     * \brief   Returns the state machine object
     **/
    inline TrafficLightFSM & self();

//////////////////////////////////////////////////////////////////////////
// Standard internal member variables
//////////////////////////////////////////////////////////////////////////
private:
    
    /**
     * \brief   The name of State Machine.
     **/
    const areg::String                mFsmName;
    /**
     * \brief   The master thread where event and timers should be processed. If nullptr, the current dispatcher value will be used.
     **/
    areg::DispatcherThread *          mMasterThread;
    /**
     * \brief   The flag, indicating whether State Machine is currently processing trigger or not.
     **/
    bool                        mProcessing;
    /**
     * \brief   The current state of State Machine.
     **/
    FsmState                      mState;    
    /**
     * \brief   The TrafficLight state-machine event consumer.
     **/
    TrafficLightEventConsumer   mEventConsumer;
    /**
     * \brief   The TrafficLight timer event consumer.
     **/
    TrafficLightTimerConsumer   mTimerConsumer;
    /**
     * \brief   The array of state to indicate state changes. For parent state, this will indicate the current active child state
     **/
    FsmState                      mCurrentStates[static_cast<int32_t>(FsmState::STATE_SIZE)]
    {
        /* UNDEFINED                 */   TrafficLightFSM::FsmState::UNDEFINED

        /* TRAFIC_LIGHT_OFF          */ , TrafficLightFSM::FsmState::UNDEFINED
        /* TRAFFIC_LIGHT_ON          */ , TrafficLightFSM::FsmState::UNDEFINED
        /* TRAFFIC_LIGHT_INITIALIZE  */ , TrafficLightFSM::FsmState::UNDEFINED
        /* TRAFFIC_LIGHT_FUNCTION    */ , TrafficLightFSM::FsmState::UNDEFINED
        /* TRAFFIC_LIGHT_YELLOW      */ , TrafficLightFSM::FsmState::UNDEFINED
        /* TRAFFIC_LIGHT_RED         */ , TrafficLightFSM::FsmState::UNDEFINED
        /* TRAFFIC_LIGHT_VEHICLE_RED */ , TrafficLightFSM::FsmState::UNDEFINED
        /* OPPOSIT_PEDESTRIAN_GREEN  */ , TrafficLightFSM::FsmState::UNDEFINED
        /* TRAFFIC_LIGHT_GREEN       */ , TrafficLightFSM::FsmState::UNDEFINED
        /* TRAFFIC_PEDESTRIAN_GREEN  */ , TrafficLightFSM::FsmState::UNDEFINED
        /* TRAFFIC_VEHICLE_GREEN     */ , TrafficLightFSM::FsmState::UNDEFINED
        /* TRAFFIC_LIGHT_START       */ , TrafficLightFSM::FsmState::UNDEFINED   

    };

//////////////////////////////////////////////////////////////////////////
// Static members. The tree structure of State Machine 
//////////////////////////////////////////////////////////////////////////
    /**
     * \brief   The fixed tree of parent states
     **/
    static constexpr    FsmState  sParrentStates[static_cast<int32_t>(FsmState::STATE_SIZE)]
    {
        /* UNDEFINED                 */   TrafficLightFSM::FsmState::UNDEFINED

        /* TRAFIC_LIGHT_OFF          */ , TrafficLightFSM::FsmState::UNDEFINED
        /* TRAFFIC_LIGHT_ON          */ , TrafficLightFSM::FsmState::UNDEFINED
        /* TRAFFIC_LIGHT_INITIALIZE  */ , TrafficLightFSM::FsmState::TRAFFIC_LIGHT_ON
        /* TRAFFIC_LIGHT_FUNCTION    */ , TrafficLightFSM::FsmState::TRAFFIC_LIGHT_ON
        /* TRAFFIC_LIGHT_YELLOW      */ , TrafficLightFSM::FsmState::TRAFFIC_LIGHT_FUNCTION
        /* TRAFFIC_LIGHT_RED         */ , TrafficLightFSM::FsmState::TRAFFIC_LIGHT_FUNCTION
        /* TRAFFIC_LIGHT_VEHICLE_RED */ , TrafficLightFSM::FsmState::TRAFFIC_LIGHT_RED
        /* OPPOSIT_PEDESTRIAN_GREEN  */ , TrafficLightFSM::FsmState::TRAFFIC_LIGHT_RED
        /* TRAFFIC_LIGHT_GREEN       */ , TrafficLightFSM::FsmState::TRAFFIC_LIGHT_FUNCTION
        /* TRAFFIC_PEDESTRIAN_GREEN  */ , TrafficLightFSM::FsmState::TRAFFIC_LIGHT_GREEN
        /* TRAFFIC_VEHICLE_GREEN     */ , TrafficLightFSM::FsmState::TRAFFIC_LIGHT_GREEN
        /* TRAFFIC_LIGHT_START       */ , TrafficLightFSM::FsmState::TRAFFIC_LIGHT_FUNCTION   
    };

    /**
     * \brief   The fixed tree of child states
     **/
    static constexpr    FsmState  sChildStates[static_cast<int32_t>(FsmState::STATE_SIZE)]
{
    /* UNDEFINED                    */     TrafficLightFSM::FsmState::UNDEFINED

    /* TRAFIC_LIGHT_OFF             */   , TrafficLightFSM::FsmState::UNDEFINED
    /* TRAFFIC_LIGHT_ON             */   , TrafficLightFSM::FsmState::TRAFFIC_LIGHT_INITIALIZE
    /* TRAFFIC_LIGHT_INITIALIZE     */   , TrafficLightFSM::FsmState::UNDEFINED
    /* TRAFFIC_LIGHT_FUNCTION       */   , TrafficLightFSM::FsmState::TRAFFIC_LIGHT_START
    /* TRAFFIC_LIGHT_YELLOW         */   , TrafficLightFSM::FsmState::UNDEFINED
    /* TRAFFIC_LIGHT_RED            */   , TrafficLightFSM::FsmState::TRAFFIC_LIGHT_VEHICLE_RED
    /* TRAFFIC_LIGHT_VEHICLE_RED    */   , TrafficLightFSM::FsmState::UNDEFINED
    /* OPPOSIT_PEDESTRIAN_GREEN     */   , TrafficLightFSM::FsmState::UNDEFINED
    /* TRAFFIC_LIGHT_GREEN          */   , TrafficLightFSM::FsmState::TRAFFIC_PEDESTRIAN_GREEN
    /* TRAFFIC_PEDESTRIAN_GREEN     */   , TrafficLightFSM::FsmState::UNDEFINED
    /* TRAFFIC_VEHICLE_GREEN        */   , TrafficLightFSM::FsmState::UNDEFINED
    /* TRAFFIC_LIGHT_START          */   , TrafficLightFSM::FsmState::UNDEFINED
};
   
//////////////////////////////////////////////////////////////////////////
// Forbidden functions / methods call
//////////////////////////////////////////////////////////////////////////
private:
    TrafficLightFSM();
    TrafficLightFSM(const TrafficLightFSM & );
    const TrafficLightFSM& operator = (const TrafficLightFSM & );
};

//////////////////////////////////////////////////////////////////////////
// TrafficLightFSM class inline functions implementation
//////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////
// Get / Set inline attributes
//////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////
// TrafficLightFSM class inline functions implementation
//////////////////////////////////////////////////////////////////////////
/**
 * \brief   Returns true if state machine is in operable state, i.e. it is not UNDEFINED
 **/
inline bool TrafficLightFSM::isOperable() const
{
    return (mState != TrafficLightFSM::FsmState::UNDEFINED);
}

/**
 * \brief   Returns the state machine object
 **/
inline TrafficLightFSM& TrafficLightFSM::self()
{
    return (*this);
}

inline bool TrafficLightFSM::isTimerActive( const NETrafficLightFSM::FsmTimer whichTimer ) const
{
    switch (whichTimer)
    {
    case NETrafficLightFSM::FsmTimer::Red:
        return mTimerRed.isActive();
        
    case NETrafficLightFSM::FsmTimer::YellowRed:
        return mTimerYellowRed.isActive();
        
    case NETrafficLightFSM::FsmTimer::Green:
        return mTimerGreen.isActive();
        
    case NETrafficLightFSM::FsmTimer::YellowGreen:
        return mTimerYellowGreen.isActive();
        
    case NETrafficLightFSM::FsmTimer::PedestrianWalk:
        return mTimerPedestrianWalk.isActive();
        
    case NETrafficLightFSM::FsmTimer::VehicleWait:
        return mTimerVehicleWait.isActive();
        
    default:
        ASSERT(false);  // wrong timer ID.
        return false;
    }
}
/**
 * \brief   Sends FSM event to be processed. By default the Event is external
 **/
inline void TrafficLightFSM::sendEvent( const NETrafficLightFSM::FsmEventValue data )
{
    if (mMasterThread != nullptr )
        NETrafficLightFSM::FsmEvent::sendEvent(NETrafficLightFSM::FsmEventData( data ), static_cast<NETrafficLightFSM::IEFsmEventConsumer &>(mEventConsumer), *mMasterThread);
    else
        NETrafficLightFSM::FsmEvent::sendEvent(NETrafficLightFSM::FsmEventData( data ), static_cast<NETrafficLightFSM::IEFsmEventConsumer &>(mEventConsumer));
}
/**
 * \brief   Returns the string value of states
 **/
inline  const char* TrafficLightFSM::getString( const TrafficLightFSM::FsmState state )
{
    switch (state)
    {
    case  TrafficLightFSM::FsmState::UNDEFINED:
        return "TrafficLightFSM::FsmState::UNDEFINED";

   case  TrafficLightFSM::FsmState::TRAFIC_LIGHT_OFF:
      return "TrafficLightFSM::FsmState::TRAFIC_LIGHT_OFF";

   case  TrafficLightFSM::FsmState::TRAFFIC_LIGHT_ON:
      return "TrafficLightFSM::FsmState::TRAFFIC_LIGHT_ON";

   case  TrafficLightFSM::FsmState::TRAFFIC_LIGHT_INITIALIZE:
      return "TrafficLightFSM::FsmState::TRAFFIC_LIGHT_INITIALIZE";

   case  TrafficLightFSM::FsmState::TRAFFIC_LIGHT_FUNCTION:
      return "TrafficLightFSM::FsmState::TRAFFIC_LIGHT_FUNCTION";

   case  TrafficLightFSM::FsmState::TRAFFIC_LIGHT_YELLOW:
      return "TrafficLightFSM::FsmState::TRAFFIC_LIGHT_YELLOW";

   case  TrafficLightFSM::FsmState::TRAFFIC_LIGHT_RED:
      return "TrafficLightFSM::FsmState::TRAFFIC_LIGHT_RED";

   case  TrafficLightFSM::FsmState::TRAFFIC_LIGHT_VEHICLE_RED:
      return "TrafficLightFSM::FsmState::TRAFFIC_LIGHT_VEHICLE_RED";

   case  TrafficLightFSM::FsmState::OPPOSIT_PEDESTRIAN_GREEN:
      return "TrafficLightFSM::FsmState::OPPOSIT_PEDESTRIAN_GREEN";

   case  TrafficLightFSM::FsmState::TRAFFIC_LIGHT_GREEN:
      return "TrafficLightFSM::FsmState::TRAFFIC_LIGHT_GREEN";

   case  TrafficLightFSM::FsmState::TRAFFIC_PEDESTRIAN_GREEN:
      return "TrafficLightFSM::FsmState::TRAFFIC_PEDESTRIAN_GREEN";

   case  TrafficLightFSM::FsmState::TRAFFIC_VEHICLE_GREEN:
      return "TrafficLightFSM::FsmState::TRAFFIC_VEHICLE_GREEN";

   case  TrafficLightFSM::FsmState::TRAFFIC_LIGHT_START:
      return "TrafficLightFSM::FsmState::TRAFFIC_LIGHT_START";

    case  TrafficLightFSM::FsmState::STATE_SIZE: // fall through
    default:
        ASSERT(false);        
        return "ERR: Unexpected TrafficLightFSM::FsmState value!";
   }
}

//////////////////////////////////////////////////////////////////////////
// End generate TrafficLightFSM.hpp file
//////////////////////////////////////////////////////////////////////////
