20_pubservice_SRC += \
    $(20_pubdatarate_BASE)/pubservice/src/ServicingComponent.cpp    \
    $(20_pubdatarate_BASE)/pubservice/src/NEUtilities.cpp           \
    $(20_pubdatarate_BASE)/pubservice/src/main.cpp
