logobserverapi_SRC += \
    $(logobserver_BASE)/lib/private/LogObserverApi.cpp              \
    $(logobserver_BASE)/lib/private/LoggerClient.cpp                \
    $(logobserver_BASE)/lib/private/ObserverMessageProcessor.cpp    \
