#pragma once

/************************************************************************
 * \file        pubservice/src/ServiceComponent.hpp
 * \ingroup     Areg SDK, Automated Real-time Event Grid Software Development Kit examples
 * \author      Artak Avetyan
 * \brief       Collection of Areg SDK examples.
 *              This file is demonstration of manual unlbocking of the request.
 ************************************************************************/
 /************************************************************************
  * Include files.
  ************************************************************************/
#include "areg/base/areg_global.h"
#include "areg/component/Component.hpp"
#include "areg/component/TimerConsumer.hpp"
#include "examples/24_pubunblock/services/HelloUnblockStub.hpp"

#include "areg/base/Stack.hpp"
#include "areg/component/Timer.hpp"

/**
 * \brief   This service receives the request and immediately manually
 *          unblocks it, so that the client(s) can send same request again.
 *          When 500 ms (HelloUnblock::ServiceTimeout) expires, it
 *          manually prepares the response and replies to the client forwarding
 *          client ID and generated by client sequence ID, so that the
 *          client can check that no response is missed or mixed.
 *          Start multiple instance of client to make sure that all responses
 *          are properly replied.
 **/
class ServiceComponent  : public  areg::Component
                        , private HelloUnblockStub
                        , private areg::TimerConsumer
{
//////////////////////////////////////////////////////////////////////////
// Internal structure
//////////////////////////////////////////////////////////////////////////
    //!< A structure to store data to send to the client(s)
    struct SessionEtnry
    {
        uint32_t    clientId{ HelloUnblock::InvalidId};   //!< Client ID
        uint32_t    seqNr   { HelloUnblock::InvalidId };  //!< The sequence ID generate by client
        uint32_t    id      { HelloUnblock::InvalidId };  //!< Request session ID used to prepare response.
    };

    //!< The stack of session entries
    using SessionList = areg::Stack<SessionEtnry>;

//////////////////////////////////////////////////////////////////////////
// Constructor / destructor
//////////////////////////////////////////////////////////////////////////
public:
    ServiceComponent( const areg::ComponentEntry & entry, areg::ComponentThread & owner );

protected:

    /**
     * \brief   This function is triggered by Component when starts up.
     * \param   holder  The holder component of service interface of Stub,
     *                  which started up.
     **/
    void startup_service_interface( areg::Component & holder ) override;

    /**
     * \brief   Request call.
     *          Request to assign an ID to the client used to call unblock request.
     * \see     responseIdentifier
     **/
    void requestIdentifier() override;

    /**
     * \brief   Request call.
     *          Request to print hello world
     * \param   clientId    The given ID of the client. Should be 0 if unknown
     * \param   seqNr       The sequence number generated by the client. On each request the client increase the sequence number
     *          and stops sending request when reach the maximum.
     * \see     responseHelloUnblock
     **/
    void requestHelloUblock( uint32_t clientId, uint32_t seqNr ) override;

    /**
     * \brief   Triggered when Timer is expired. 
     * \param   timer   The timer object that is expired.
     **/
    void process_timer( areg::Timer & timer ) override;

//////////////////////////////////////////////////////////////////////////
// Hidden methods
//////////////////////////////////////////////////////////////////////////
private:
    inline ServiceComponent & self ()
    {
        return (*this);
    }

    inline void printRequest( uint32_t clientId, uint32_t seqNr, uint32_t sessionId );

    inline void printResponse( uint32_t clientId, uint32_t seqNr, uint32_t sessionId );

//////////////////////////////////////////////////////////////////////////
// Member variables
//////////////////////////////////////////////////////////////////////////
private:
    SessionList     mSessionList;   //!< The list of sessions to track.
    areg::Timer           mTimer;         //!< Timer to unlock request.

//////////////////////////////////////////////////////////////////////////
// Forbidden calls
//////////////////////////////////////////////////////////////////////////
private:
    ServiceComponent() = delete;
    AREG_NOCOPY_NOMOVE( ServiceComponent );
};
