areg_SRC += \
	$(areg_BASE)/persist/private/ConfigManager.cpp			\
	$(areg_BASE)/persist/private/IEConfigurationListener.cpp\
	$(areg_BASE)/persist/private/IEDatabaseEngine.cpp		\
	$(areg_BASE)/persist/private/NEPersistence.cpp			\
	$(areg_BASE)/persist/private/PersistenceManager.cpp		\
	$(areg_BASE)/persist/private/Property.cpp				\
	$(areg_BASE)/persist/private/PropertyKey.cpp			\
	$(areg_BASE)/persist/private/PropertyValue.cpp			\
