extend_SRC  +=  \
    ${extend_BASE}/console/private/Console.cpp                  \
    ${extend_BASE}/console/private/OptionParser.cpp             \
    ${extend_BASE}/console/private/SystemServiceConsole.cpp     \
    ${extend_BASE}/console/private/ansi/ConsoleAnsi.cpp         \
    ${extend_BASE}/console/private/ncurses/ConsoleNcurses.cpp   \
    ${extend_BASE}/console/private/win32/ConsoleWin32.cpp       \
