logobserver_BASE        := $(AREG_BASE)/logobserver

OBSERVER_API_IMPORT     :=
OBSERVER_API_PATH       :=

include $(logobserver_BASE)/lib/Makefile
include $(logobserver_BASE)/app/Makefile


observer: logobserverapi logobserver

.PHONY: observer
