#ifndef AREG_LOGCOLLECTOR_SERVICE_LOGCOLLECTORSERVERSERVICE_HPP
#define AREG_LOGCOLLECTOR_SERVICE_LOGCOLLECTORSERVERSERVICE_HPP
/************************************************************************
 * This file is part of the Areg SDK core engine.
 * Areg SDK is dual-licensed under Free open source (Apache version 2.0
 * License) and Commercial (with various pricing models) licenses, depending
 * on the nature of the project (commercial, research, academic or free).
 * You should have received a copy of the Areg SDK license description in LICENSE.txt.
 * If not, please contact to info[at]areg.tech
 *
 * \copyright   (c) 2017-2026 Aregtech UG. All rights reserved.
 * \file        logcollector/service/LogCollectorServerService.hpp
 * \ingroup     Areg SDK, Automated Real-time Event Grid Software Development Kit
 * \author      Artak Avetyan
 * \brief       Areg Platform, Log Collector server connection service
 ************************************************************************/

/************************************************************************
 * Include files.
 ************************************************************************/
#include "areg/base/GEGlobal.h"
#include "areg/component/TimerConsumer.hpp"

#include "areg/component/Timer.hpp"
#include "areg/logging/LoggingDefs.hpp"
#include "aregextend/service/ServiceCommunicationBase.hpp"
#include "logcollector/service/private/LogCollectorMessageProcessor.hpp"

//////////////////////////////////////////////////////////////////////////
// LogCollectorServerService class declaration
//////////////////////////////////////////////////////////////////////////
/**
 * \brief   The server side connection service. Used by message router to
 *          accept service connections.
 **/
class LogCollectorServerService : public    aregext::ServiceCommunicationBase
                                , private   areg::TimerConsumer
{
//////////////////////////////////////////////////////////////////////////
// Friend classes to access internals
//////////////////////////////////////////////////////////////////////////
    friend class LogCollectorMessageProcessor;

//////////////////////////////////////////////////////////////////////////
// Internal constants
//////////////////////////////////////////////////////////////////////////
private:

    //!< The timeout waiting to save config.
    static constexpr uint32_t   TIMEOUT_SAVE_CONFIG{ areg::WAIT_1_SECOND };

//////////////////////////////////////////////////////////////////////////
// Constructor / Destructor
//////////////////////////////////////////////////////////////////////////
public:
    /**
     * \brief   Default constructor to initialize default values.
     **/
    LogCollectorServerService();
    /**
     * \brief   Destructor
     **/
    virtual ~LogCollectorServerService() = default;

//////////////////////////////////////////////////////////////////////////
// Attributes
//////////////////////////////////////////////////////////////////////////
public:
    /**
     * \brief   Returns the list of log observers.
     */
    inline const areg::MapInstances & getObservers() const;

    /**
     * \brief   Dispatches and forwards the message generated by the log collector
     *          to the clients or to the observers.
     * \param   msgForward  The message to dispatch and forward.
     **/
    void dispatchAndForwardLoggerMessage(const areg::RemoteMessage& msgForward);

public:
/************************************************************************/
// ServiceCommunicationBase overrides
/************************************************************************/
    /**
     * \brief   Adds an entry into the list of connected instances.
     * \param   cookie      The cookie of connected instance.
     * \param   instance    The name of the connected instance.
     **/
    void addInstance(const ITEM_ID & cookie, const areg::ConnectedInstance & instance ) override;

    /**
     * \brief   Removes connected instance.
     * \param   cookie      The cookie of connected instance.
     **/
    void removeInstance(const ITEM_ID & cookie ) override;

    /**
     * \brief   Removes all connected instances from the map.
     **/
    void removeAllInstances() override;

//////////////////////////////////////////////////////////////////////////
// Overrides
//////////////////////////////////////////////////////////////////////////
protected:

    /**
     * \brief   Triggered when remote service connection and communication channel is established.
     * \param   channel     The connection and communication channel of remote service.
     **/
    void connectedRemoteServiceChannel( const areg::Channel & channel ) override;

    /**
     * \brief   Triggered when disconnected remote service connection and communication channel.
     * \param   channel     The connection and communication channel of remote service.
     **/
    void disconnectedRemoteServiceChannel( const areg::Channel & channel ) override;

    /**
     * \brief   Triggered when remote service connection and communication channel is lost.
     *          The connection is considered lost if it not possible to read or
     *          receive data, and it was not stopped by API call.
     * \param   channel     The connection and communication channel of remote service.
     **/
    void lostRemoteServiceChannel( const areg::Channel & channel ) override;

/************************************************************************/
// RemoteMessageHandler interface overrides
/************************************************************************/

    /**
     * \brief   Triggered, when failed to process message, i.e. the target for message processing was not found.
     *          In case of request message processing, the source should receive error notification.
     * \param   msgUnprocessed  Unprocessed message data.
     **/
    void failedProcessMessage( const areg::RemoteMessage & msgUnprocessed ) override;

/************************************************************************/
// ServiceEventConsumer overrides
/************************************************************************/

    /**
     * \brief   Called when receive event the client connection is started.
     **/
    void onServiceConnectionStarted() override;

    /**
     * \brief   Called when receive event the client connection is stopped.
     **/
    void onServiceConnectionStopped() override;

    /**
     * \brief   Called when receive event the client connection is lost.
     **/
    void onServiceConnectionLost() override;

    /**
     * \brief   Called when received a communication message to dispatch and process.
     * \param   msgReceived     The received the communication message. 
     **/
    void onServiceMessageReceived(const areg::RemoteMessage & msgReceived) override;

    /**
     * \brief   Called when need to send a communication message.
     * \param   msgSend     The communication message to send. 
     **/
    void onServiceMessageSend(const areg::RemoteMessage & msgSend) override;

/************************************************************************/
// TimerConsumer interface overrides.
/************************************************************************/

    /**
     * \brief   Triggered when Timer is expired. 
     *          The passed Timer parameter is indicating object, which has been expired.
     *          Overwrite method to receive messages.
     * \param   timer   The timer object that is expired.
     **/
    void processTimer( areg::Timer & timer ) override;

//////////////////////////////////////////////////////////////////////////
// Hidden methods.
//////////////////////////////////////////////////////////////////////////
private:
    /**
     * \brief   Returns instance of object. For internal use only.
     **/
    inline LogCollectorServerService & self();

//////////////////////////////////////////////////////////////////////////////
// Member variables
//////////////////////////////////////////////////////////////////////////////
private:
    //!< The Log Collector message processor
    LogCollectorMessageProcessor    mLoggerProcessor;
    //!< List of log observers (log viewers)
    areg::MapInstances         mObservers;
    //!< The timer used when trigger multiple requests to save configuration.
    areg::Timer                           mSaveTimer;

//////////////////////////////////////////////////////////////////////////////
// Forbidden calls.
//////////////////////////////////////////////////////////////////////////////
private:
    AREG_NOCOPY_NOMOVE( LogCollectorServerService );
};

//////////////////////////////////////////////////////////////////////////////
// LogCollectorServerService class inline functions implementation
//////////////////////////////////////////////////////////////////////////////

inline const areg::MapInstances & LogCollectorServerService::getObservers() const
{
    return mObservers;
}

inline LogCollectorServerService & LogCollectorServerService::self()
{
    return (*this);
}

#endif  // AREG_LOGCOLLECTOR_SERVICE_LOGCOLLECTORSERVERSERVICE_HPP
