#ifndef AREG_LOGCOLLECTOR_SERVICE_LOGCOLLECTORSERVERSERVICE_HPP
#define AREG_LOGCOLLECTOR_SERVICE_LOGCOLLECTORSERVERSERVICE_HPP
/************************************************************************
 * This file is part of the Areg SDK core engine.
 * Areg SDK is dual-licensed under Free open source (Apache version 2.0
 * License) and Commercial (with various pricing models) licenses, depending
 * on the nature of the project (commercial, research, academic or free).
 * You should have received a copy of the Areg SDK license description in LICENSE.txt.
 * If not, please contact to info[at]areg.tech
 *
 * \copyright   (c) 2017-2026 Aregtech UG. All rights reserved.
 * \file        logcollector/service/LogCollectorServerService.hpp
 * \ingroup     Areg SDK, Automated Real-time Event Grid Software Development Kit
 * \author      Artak Avetyan
 * \brief       Areg Platform, Log Collector server connection service
 ************************************************************************/

/************************************************************************
 * Include files.
 ************************************************************************/
#include "areg/base/areg_global.h"
#include "areg/component/TimerConsumer.hpp"

#include "areg/component/Timer.hpp"
#include "areg/logging/LoggingDefs.hpp"
#include "aregextend/service/ServiceCommunicationBase.hpp"
#include "logcollector/service/private/LogCollectorMessageProcessor.hpp"

//////////////////////////////////////////////////////////////////////////
// LogCollectorServerService class declaration
//////////////////////////////////////////////////////////////////////////
/**
 * \brief   The server side connection service. Used by message router to
 *          accept service connections.
 **/
class LogCollectorServerService final   : public    areg::ext::ServiceCommunicationBase
                                        , private   areg::TimerConsumer
{
//////////////////////////////////////////////////////////////////////////
// Friend classes to access internals
//////////////////////////////////////////////////////////////////////////
    friend class LogCollectorMessageProcessor;

//////////////////////////////////////////////////////////////////////////
// Internal constants
//////////////////////////////////////////////////////////////////////////
private:

    //!< The timeout waiting to save config.
    static constexpr uint32_t   TIMEOUT_SAVE_CONFIG{ areg::WAIT_1_SECOND };

//////////////////////////////////////////////////////////////////////////
// Constructor / Destructor
//////////////////////////////////////////////////////////////////////////
public:
    LogCollectorServerService();
    virtual ~LogCollectorServerService() = default;

//////////////////////////////////////////////////////////////////////////
// Attributes
//////////////////////////////////////////////////////////////////////////
public:
    inline const areg::MapInstances & observers() const;

    /**
     * \brief   Dispatches and forwards the message generated by the log collector to the clients or
     *          to the observers.
     *
     * \param   msgForward      The message to dispatch and forward.
     **/
    void dispatch_and_forward_logger_message(const areg::EventEnvelope& msgForward);

public:
/************************************************************************/
// ServiceCommunicationBase overrides
/************************************************************************/
    /**
     * \brief   Adds an entry into the list of connected instances.
     *
     * \param   cookie      The cookie of connected instance.
     * \param   instance    The name of the connected instance.
     **/
    void add_instance(const ITEM_ID & cookie, const areg::ConnectedInstance & instance ) final;

    /**
     * \brief   Removes a connected instance.
     *
     * \param   cookie      The cookie of connected instance.
     **/
    void remove_instance(const ITEM_ID & cookie ) final;

    /**
     * \brief   Removes all connected instances from the map.
     **/
    void remove_all_instances() final;

//////////////////////////////////////////////////////////////////////////
// Overrides
//////////////////////////////////////////////////////////////////////////
protected:

    /**
     * \brief   Triggered when remote service connection and communication channel is established.
     *
     * \param   channel     The connection and communication channel of remote service.
     **/
    void on_service_channel_connected( const areg::Channel & channel ) final;

    /**
     * \brief   Triggered when remote service connection and communication channel is disconnected.
     *
     * \param   channel     The connection and communication channel of remote service.
     **/
    void on_service_channel_disconnected( const areg::Channel & channel ) final;

    /**
     * \brief   Triggered when remote service connection and communication channel is lost. The
     *          connection is considered lost if it not possible to read or receive data, and it was
     *          not stopped by API call.
     *
     * \param   channel     The connection and communication channel of remote service.
     **/
    void on_service_channel_lost( const areg::Channel & channel ) final;

/************************************************************************/
// RemoteMessageHandler interface overrides
/************************************************************************/

    /**
     * \brief   Triggered when failed to process message, i.e. the target for message processing was
     *          not found. In case of request message processing, the source should receive error
     *          notification.
     *
     * \param   msgUnprocessed      Unprocessed message data.
     **/
    void failed_process_message( const areg::EventEnvelope & msgUnprocessed ) final;

/************************************************************************/
// ServiceEventConsumer overrides
/************************************************************************/

    /**
     * \brief   Triggered when the client connection is started.
     **/
    void on_connection_started() final;

    /**
     * \brief   Triggered when the client connection is stopped.
     **/
    void on_connection_stopped() final;

    /**
     * \brief   Triggered when the client connection is lost.
     **/
    void on_connection_lost() final;

    /**
     * \brief   Triggered when a communication message is received to be dispatched and processed.
     *
     * \param   msgReceived     The received communication message.
     **/
    void on_message_received(const areg::EventEnvelope & msgReceived) final;

    /**
     * \brief   Triggered when a communication message needs to be sent.
     *
     * \param   msgSend     The communication message to send.
     **/
    void on_message_send(const areg::EventEnvelope & msgSend) final;

/************************************************************************/
// TimerConsumer interface overrides.
/************************************************************************/

    /**
     * \brief   Triggered when the timer expires.
     *
     * \param   timer       The timer object that has expired.
     **/
    void process_timer( areg::Timer & timer ) final;

//////////////////////////////////////////////////////////////////////////
// Hidden methods.
//////////////////////////////////////////////////////////////////////////
private:
    inline LogCollectorServerService & self();

//////////////////////////////////////////////////////////////////////////////
// Member variables
//////////////////////////////////////////////////////////////////////////////
private:
    //!< The Log Collector message processor
    LogCollectorMessageProcessor    mLoggerProcessor;
    //!< List of log observers (log viewers)
    areg::MapInstances              mObservers;
    //!< The timer used when trigger multiple requests to save configuration.
    areg::Timer                     mSaveTimer;

//////////////////////////////////////////////////////////////////////////////
// Forbidden calls.
//////////////////////////////////////////////////////////////////////////////
private:
    AREG_NOCOPY_NOMOVE( LogCollectorServerService );
};

//////////////////////////////////////////////////////////////////////////////
// LogCollectorServerService class inline functions implementation
//////////////////////////////////////////////////////////////////////////////

inline const areg::MapInstances & LogCollectorServerService::observers() const
{
    return mObservers;
}

inline LogCollectorServerService & LogCollectorServerService::self()
{
    return (*this);
}

#endif  // AREG_LOGCOLLECTOR_SERVICE_LOGCOLLECTORSERVERSERVICE_HPP
