11_svcmix_SRC += \
	$(11_svcmix_BASE)/src/ClientComponent.cpp \
	$(11_svcmix_BASE)/src/MainComponent.cpp \
	$(11_svcmix_BASE)/src/SecondaryComponent.cpp \
	$(11_svcmix_BASE)/src/ServiceClient.cpp \
	$(11_svcmix_BASE)/src/ServicingComponent.cpp \
	$(11_svcmix_BASE)/src/main.cpp
