areg_SRC += \
	$(areg_BASE)/trace/private/DebugOutputLogger.cpp \
	$(areg_BASE)/trace/private/ELayouts.cpp \
	$(areg_BASE)/trace/private/FileLogger.cpp \
	$(areg_BASE)/trace/private/IETraceConfiguration.cpp \
	$(areg_BASE)/trace/private/LayoutManager.cpp \
	$(areg_BASE)/trace/private/LogMessage.cpp \
	$(areg_BASE)/trace/private/LoggerBase.cpp \
	$(areg_BASE)/trace/private/NELogConfig.cpp \
	$(areg_BASE)/trace/private/NETrace.cpp \
	$(areg_BASE)/trace/private/TraceEvent.cpp \
	$(areg_BASE)/trace/private/TraceManager.cpp \
	$(areg_BASE)/trace/private/TraceMessage.cpp \
	$(areg_BASE)/trace/private/TraceProperty.cpp \
	$(areg_BASE)/trace/private/TracePropertyKey.cpp \
	$(areg_BASE)/trace/private/TracePropertyValue.cpp \
	$(areg_BASE)/trace/private/TraceScope.cpp \
