#!/usr/bin/env python3
"""Write docs/agent/members.json: every member name the public headers declare.

check_contract.py rule B-08 reports a snake_case call on an areg object whose
name is on no public header. The list is generated rather than curated, so a
framework rename cannot leave it behind, and check_corpus.py regenerates it and
fails when the file on disk differs.

    python3 tools/agent/build_members.py            # rewrite the file
    python3 tools/agent/build_members.py --check    # exit 1 when it is stale
"""
import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
FRAMEWORK = os.path.join(ROOT, 'framework', 'areg')
TARGET = os.path.join(ROOT, 'docs', 'agent', 'members.json')

# A declaration or a definition whose name is snake_case: the shape every public
# framework method has since the rename.
DECLARATION = re.compile(r'^\s*(?:[A-Za-z_][\w:<>,\s\*&]*?\s+)?([a-z][a-z0-9_]*)\s*\(')

# "operator uint32_t (" and "operator bool()" put a type where a name would be. A
# conversion is reached through the type, never through a member call.
CONVERSION = re.compile(r'\boperator\s*$')

# A statement in an inline body has the shape of a declaration: "if (", "return (",
# "switch (". Every one of them is spelled with a reserved word, and so is every
# fundamental type, so the two closed lists below separate them from member names.
KEYWORDS = frozenset("""
alignas alignof and and_eq asm auto bitand bitor bool break case catch char char8_t
char16_t char32_t class compl concept const consteval constexpr constinit const_cast
continue co_await co_return co_yield decltype default delete do double dynamic_cast
else enum explicit export extern false float for friend goto if inline int long
mutable namespace new noexcept not not_eq nullptr operator or or_eq private protected
public register reinterpret_cast requires return short signed sizeof static
static_assert static_cast struct switch template this thread_local throw true try
typedef typeid typename union unsigned using virtual void volatile wchar_t while xor
xor_eq
""".split())

FIXED_WIDTH = frozenset(
    ['size_t', 'ssize_t', 'ptrdiff_t', 'intptr_t', 'uintptr_t', 'intmax_t', 'uintmax_t']
    + ['{}int{}_t'.format(sign, width)
       for sign in ('', 'u')
       for width in ('8', '16', '32', '64',
                     '_least8', '_least16', '_least32', '_least64',
                     '_fast8', '_fast16', '_fast32', '_fast64')])

NOT_A_MEMBER = KEYWORDS | FIXED_WIDTH


def collect(framework):
    """Every snake_case member name declared outside a private folder."""
    names = set()
    headers = 0
    for base, dirs, files in os.walk(framework):
        dirs[:] = [d for d in dirs if d != 'private']
        for name in files:
            if not name.endswith(('.hpp', '.h')):
                continue
            headers += 1
            path = os.path.join(base, name)
            with open(path, encoding='utf-8', errors='ignore') as handle:
                for line in handle:
                    found = DECLARATION.match(line)
                    if not found:
                        continue
                    if found.group(1) in NOT_A_MEMBER:
                        continue
                    if CONVERSION.search(line[:found.start(1)]):
                        continue
                    names.add(found.group(1))
    return headers, sorted(names)


def document(headers, names):
    return {
        'description': 'Every snake_case name the public areg headers declare or '
                       'call. A named call on an areg object whose name is absent '
                       'here exists nowhere in the framework. Operators are outside '
                       'this list entirely, so absence here says nothing about them: '
                       'read docs/agent/21-data-types.md and 40-base-api.md, and note '
                       'that String and WideString carry + and +=. C++ keywords, '
                       'fundamental and fixed-width type names, and conversion '
                       'operators are not members and are excluded.',
        'source': 'generated by tools/agent/build_members.py from framework/areg, '
                  'excluding every private/ folder. A name an inline body calls is '
                  'kept: a name too many can only miss a defect, where a name too '
                  'few reports correct code as wrong.',
        'headers': headers,
        'members': names,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--check', action='store_true',
                        help='exit 1 when the file on disk is not what this writes')
    args = parser.parse_args()

    if not os.path.isdir(FRAMEWORK):
        sys.stderr.write('error: no framework tree at {}\n'.format(FRAMEWORK))
        return 2
    headers, names = collect(FRAMEWORK)
    if not names:
        sys.stderr.write('error: no member names found under {}\n'.format(FRAMEWORK))
        return 2
    fresh = document(headers, names)

    if args.check:
        try:
            with open(TARGET, encoding='utf-8') as handle:
                on_disk = json.load(handle)
        except (OSError, ValueError) as error:
            sys.stderr.write('error: cannot read {}: {}\n'.format(TARGET, error))
            return 1
        if on_disk.get('members') != fresh['members']:
            missing = sorted(set(fresh['members']) - set(on_disk.get('members') or []))
            extra = sorted(set(on_disk.get('members') or []) - set(fresh['members']))
            sys.stderr.write('error: docs/agent/members.json is stale: '
                             '{} name(s) added, {} removed. Run '
                             'tools/agent/build_members.py\n'
                             .format(len(missing), len(extra)))
            return 1
        print('members.json is current: {} names from {} headers'
              .format(len(fresh['members']), headers))
        return 0

    with open(TARGET, 'w', encoding='utf-8') as handle:
        json.dump(fresh, handle, indent=1)
        handle.write('\n')
    print('wrote {}: {} names from {} headers'
          .format(os.path.relpath(TARGET, ROOT), len(names), headers))
    return 0


if __name__ == '__main__':
    sys.exit(main())
