#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# This file is part of the AREG SDK.
#
# Writes the small file a particular coding agent looks for, containing nothing
# but a pointer to AGENTS.md.
#
# Why this exists
# ---------------
# AGENTS.md is the one entry point for building an application on top of areg.
# It is deliberately agent-neutral: no harness is named in it, and no harness
# gets its own copy of its contents.
#
# Harnesses disagree about which file they read on startup, and several of them
# never look at AGENTS.md. Tracking one instruction file per harness would mean
# n copies of the same guidance drifting apart, and the repository silently
# taking sides. So the redirects are generated locally instead, and stay out of
# version control. The single exception is .github/copilot-instructions.md,
# which is tracked because it predates this tool; it is a pure redirect and must
# stay one.
#
# Usage
# -----
#   python tools/agent/setup_agent_redirect.py --list
#   python tools/agent/setup_agent_redirect.py --harness claude
#   python tools/agent/setup_agent_redirect.py --all
#   python tools/agent/setup_agent_redirect.py --check
#
# No third-party imports, no network, and nothing outside the repository is
# written.
# ---------------------------------------------------------------------------

from __future__ import annotations

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# One row per harness: the file it reads, relative to the repository root, in
# that harness's own separator-free form. A harness whose entry point already is
# AGENTS.md is listed with None and reported as needing nothing.
HARNESSES = {
    'agents': (None, 'reads AGENTS.md directly'),
    'codex': (None, 'reads AGENTS.md directly'),
    'copilot': ('.github/copilot-instructions.md', 'GitHub Copilot'),
    'claude': ('CLAUDE.md', 'Claude Code'),
    'cursor': ('.cursor/rules/areg.mdc', 'Cursor'),
    'windsurf': ('.windsurfrules', 'Windsurf'),
    'cline': ('.clinerules', 'Cline'),
    'continue': ('.continuerules', 'Continue'),
    'gemini': ('GEMINI.md', 'Gemini CLI'),
    'aider': ('CONVENTIONS.md', 'Aider'),
}

# The one redirect that is tracked, and so must not be rewritten by this tool
# without being asked twice.
TRACKED = '.github/copilot-instructions.md'

BODY = """{fence}
# AREG SDK

This file exists only so that {label} lands in the right place. It holds no
content of its own, and it is not the source of anything.

**Read [`AGENTS.md`]({up}AGENTS.md) in the repository root.** It routes every task to
the one page that answers it.

`AGENTS.md` covers one job: **building an application on top of areg**. Read it, then
the single row of its task table that matches your task, and nothing else. Changing
the areg framework itself is a different job that the agent documentation does not
describe; start from [`CONTRIBUTING.md`]({up}CONTRIBUTING.md) for that.

Do not search the repository before reading `AGENTS.md`. It exists to stop exactly
that.

<!-- Generated by tools/agent/setup_agent_redirect.py. Edit AGENTS.md, never this file. -->
"""

# Cursor reads a front-matter header and applies the rule only when it matches.
FENCE = {
    '.cursor/rules/areg.mdc': '---\ndescription: AREG SDK entry point\nalwaysApply: true\n---\n',
}


def target_path(rel: str) -> str:
    return os.path.join(ROOT, *rel.split('/'))


def depth_prefix(rel: str) -> str:
    """The ../ needed to reach the repository root from the redirect's folder."""
    return '../' * rel.count('/')


def render(rel: str, label: str) -> str:
    return BODY.format(fence=FENCE.get(rel, ''), label=label, up=depth_prefix(rel))


def write(name: str, force: bool) -> int:
    rel, label = HARNESSES[name]
    if rel is None:
        print('{:<10} nothing to write, it {}'.format(name, label))
        return 0

    path = target_path(rel)
    wanted = render(rel, label)

    if os.path.isfile(path):
        with open(path, 'r', encoding='utf-8') as handle:
            current = handle.read()
        if current == wanted:
            print('{:<10} {} already current'.format(name, rel))
            return 0
        if rel == TRACKED and not force:
            print('{:<10} {} is tracked and differs; pass --force to '
                  'overwrite'.format(name, rel))
            return 1
        if not force:
            print('{:<10} {} exists and differs; pass --force to '
                  'overwrite'.format(name, rel))
            return 1

    folder = os.path.dirname(path)
    if folder and not os.path.isdir(folder):
        os.makedirs(folder)
    with open(path, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(wanted)
    print('{:<10} wrote {}'.format(name, rel))
    return 0


def check() -> int:
    """Report which redirects exist and whether they are still pure redirects."""
    bad = 0
    for name in sorted(HARNESSES):
        rel, label = HARNESSES[name]
        if rel is None:
            continue
        path = target_path(rel)
        if not os.path.isfile(path):
            continue
        with open(path, 'r', encoding='utf-8') as handle:
            text = handle.read()
        pure = 'AGENTS.md' in text and len(text) <= 2 * len(render(rel, label))
        print('{:<10} {:<38} {}'.format(name, rel,
                                        'redirect' if pure else 'HAS OWN CONTENT'))
        if not pure:
            bad += 1
    if bad:
        print('\n{} file(s) hold guidance of their own. That guidance will drift '
              'from AGENTS.md.\nSee CONTRIBUTING.md section 4f.'.format(bad))
    return 1 if bad else 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description='Write the local redirect file a coding agent looks for, '
                    'pointing it at AGENTS.md.')
    parser.add_argument('--harness', action='append', default=[],
                        help='harness to write a redirect for; repeatable')
    parser.add_argument('--all', action='store_true',
                        help='write a redirect for every known harness')
    parser.add_argument('--list', action='store_true',
                        help='list the known harnesses and exit')
    parser.add_argument('--check', action='store_true',
                        help='report existing redirects that hold content of '
                             'their own, and exit non-zero if any do')
    parser.add_argument('--force', action='store_true',
                        help='overwrite a file that exists and differs')
    args = parser.parse_args()

    if args.list:
        width = max(len(n) for n in HARNESSES)
        for name in sorted(HARNESSES):
            rel, label = HARNESSES[name]
            print('{:<{w}}  {:<38} {}'.format(name, rel or '-', label, w=width))
        return 0

    if args.check:
        return check()

    names = sorted(HARNESSES) if args.all else args.harness
    if not names:
        parser.print_help()
        return 2

    unknown = [n for n in names if n not in HARNESSES]
    if unknown:
        print('unknown harness: {}\nrun with --list to see the known '
              'ones'.format(', '.join(unknown)), file=sys.stderr)
        return 2

    status = 0
    for name in names:
        status |= write(name, args.force)

    print('\nThese files are ignored by git on purpose. AGENTS.md is the source; '
          'a redirect\nnever holds guidance of its own. See CONTRIBUTING.md '
          'section 4f.')
    return status


if __name__ == '__main__':
    sys.exit(main())
