mcrouter_SRC += \
    $(mcrouter_BASE)/app/private/MulticastRouter.cpp            \
    $(mcrouter_BASE)/app/private/NEMulticastRouterSettings.cpp  \
    $(mcrouter_BASE)/app/private/RouterConsoleService.cpp       \
    $(mcrouter_BASE)/app/private/posix/MulticastRouterPosix.cpp \
    $(mcrouter_BASE)/app/private/win32/MulticastRouterWin32.cpp \
