24_subscribermulti_SRC += \
	$(24_pubsubmulti_BASE)/subscribermulti/src/SubscriberBase.cpp	\
	$(24_pubsubmulti_BASE)/subscribermulti/src/Subscriber.cpp		\
	$(24_pubsubmulti_BASE)/subscribermulti/src/SubscriberSecond.cpp	\
	$(24_pubsubmulti_BASE)/subscribermulti/src/main.cpp
