11_locsvcmesh_SRC += \
    $(11_locmesh_BASE)/locsvcmesh/src/ClientComponent.cpp		\
    $(11_locmesh_BASE)/locsvcmesh/src/ServiceClient.cpp         \
    $(11_locmesh_BASE)/locsvcmesh/src/ServiceHelloWorld.cpp		\
    $(11_locmesh_BASE)/locsvcmesh/src/ServicingComponents.cpp   \
    $(11_locmesh_BASE)/locsvcmesh/src/main.cpp
