11_locsvcmesh_SRC += \
	$(11_locmesh_BASE)/locsvcmesh/src/ClientComponent.cpp \
	$(11_locmesh_BASE)/locsvcmesh/src/MainComponent.cpp \
	$(11_locmesh_BASE)/locsvcmesh/src/SecondaryComponent.cpp \
	$(11_locmesh_BASE)/locsvcmesh/src/ServiceClient.cpp \
	$(11_locmesh_BASE)/locsvcmesh/src/ServicingComponent.cpp \
	$(11_locmesh_BASE)/locsvcmesh/src/main.cpp
