observer_BASE	:= $(AREG_BASE)/observer

logobserver_TARGET_BIN  :=
observer_lib_TARGET_BIN :=

OBSERVER_API_IMPORT     :=
OBSERVER_API_PATH       :=

include $(observer_BASE)/lib/Makefile
include $(observer_BASE)/app/Makefile


observer: observerapi logobserver

.PHONY: observer
