
//////////////////////////////////////////////////////////////////////////
// Begin generate IETrafficLightActionHandler.cpp file
//////////////////////////////////////////////////////////////////////////

/************************************************************************
 * (c) copyright    2021 - 2024
 *                  Generated by AREGtech code generator tool.
 * Generated at     16.08.2021  12:45:39 GMT+02:00 
 ************************************************************************/

/************************************************************************
 * \file            pubservice/src/IETrafficLightActionHandler.cpp
 * \ingroup         TrafficLight State Machine
 * \brief           This is an automatic generated code of TrafficLight action handler.
 ************************************************************************/

/************************************************************************
 * Include files
 ************************************************************************/

#include "pubservice/src/IETrafficLightActionHandler.hpp"

//////////////////////////////////////////////////////////////////////////
// End generate IETrafficLightActionHandler.cpp file
//////////////////////////////////////////////////////////////////////////
