
23_common_SRC += \
    $(23_pubsubmix_BASE)/common/src/NECommon.cpp    \
    $(23_pubsubmix_BASE)/common/src/Publisher.cpp   \
    $(23_pubsubmix_BASE)/common/src/PubSubMixed.cpp \
    $(23_pubsubmix_BASE)/common/src/Subscriber.cpp  \
