include $(AREG_BASE)/areg/Makefile
include $(AREG_BASE)/extensions/Makefile
include $(AREG_BASE)/mcrouter/Makefile
include $(AREG_BASE)/logger/Makefile


framework: areg extensions mcrouter logger

.PHONY: framework
