include $(AREG_BASE)/areg/Makefile
include $(AREG_BASE)/extend/Makefile
include $(AREG_BASE)/mcrouter/Makefile
include $(AREG_BASE)/logger/Makefile
include $(AREG_BASE)/observer/Makefile


framework: areg extend mcrouter logger observer

.PHONY: framework
