mcrouter_SRC += \
	$(mcrouter_BASE)/tcp/private/IEServerConnectionHandler.cpp \
	$(mcrouter_BASE)/tcp/private/ListServiceProxies.cpp \
	$(mcrouter_BASE)/tcp/private/ServerConnection.cpp \
	$(mcrouter_BASE)/tcp/private/ServerReceiveThread.cpp \
	$(mcrouter_BASE)/tcp/private/ServerSendThread.cpp \
	$(mcrouter_BASE)/tcp/private/ServerService.cpp \
	$(mcrouter_BASE)/tcp/private/ServerServiceEvent.cpp \
	$(mcrouter_BASE)/tcp/private/ServiceProxy.cpp \
	$(mcrouter_BASE)/tcp/private/ServiceRegistry.cpp \
	$(mcrouter_BASE)/tcp/private/ServiceStub.cpp \
