mcrouter_SRC += \
	${mcrouter_BASE}/tcp/private/ListServiceProxies.cpp		\
	${mcrouter_BASE}/tcp/private/RouterServerService.cpp	\
	${mcrouter_BASE}/tcp/private/ServiceProxy.cpp			\
	${mcrouter_BASE}/tcp/private/ServiceRegistry.cpp		\
	${mcrouter_BASE}/tcp/private/ServiceStub.cpp			\
