#ifndef AREG_LOGGING_PRIVATE_LOGGINGEVENT_HPP
#define AREG_LOGGING_PRIVATE_LOGGINGEVENT_HPP
/************************************************************************
 * This file is part of the Areg SDK core engine.
 * Areg SDK is dual-licensed under Free open source (Apache version 2.0
 * License) and Commercial (with various pricing models) licenses, depending
 * on the nature of the project (commercial, research, academic or free).
 * You should have received a copy of the Areg SDK license description in LICENSE.txt.
 * If not, please contact to info[at]areg.tech
 *
 * \copyright   (c) 2017-2026 Aregtech UG. All rights reserved.
 * \file        areg/logging/private/LoggingEvent.hpp
 * \ingroup     Areg SDK, Automated Real-time Event Grid Software Development Kit
 * \author      Artak Avetyan
 * \brief       Areg Platform, The logging thread, which is receiving logging events and performs log operations.
 ************************************************************************/
/************************************************************************
 * Include files.
 ************************************************************************/
#include "areg/base/areg_global.h"
#include "areg/component/EventTemplate.hpp"
#include "areg/logging/LoggingDefs.hpp"

#if AREG_LOGGING

namespace areg {

//////////////////////////////////////////////////////////////////////////
// LoggingEventData class declaration
//////////////////////////////////////////////////////////////////////////
/**
 * \brief   The tracing (or logging) event is triggered each time when application
 *          needs a logging action to be performed. The event is forwarded to a logging thread
 *          for further processing, like configuring logging, output message, etc.
 *          The logging event contains data with the instruction to perform certain actions.
 *          This logging event data is automatically generated by system, when a certain API is called.
 **/
class LoggingEventData
{
//////////////////////////////////////////////////////////////////////////
// Internal types and constants
//////////////////////////////////////////////////////////////////////////
public:
    /**
     * \brief   LoggingEventData::LogAction
     *          The list of supported actions for logging.
     **/
    enum class LogAction    : uint8_t
    {
          Undefined     //!< Action is undefined, do nothing
        , StartLogs     //!< Action to notify to start logging
        , StopLogs      //!< Action to notify to stop logging
        , EnableLogs    //!< Action to notify to enable logging
        , DisableLogs   //!< Action to notify to stop logging
        , SaveScopes    //!< Action to notify to save scope list
        , LogMessage    //!< Action to output logging message
        , UpdateScopes  //!< Action to update scope priorities
        , QueryScopes   //!< Action to send the list of scopes.
    };

    /**
     * \brief   Converts and returns the string representation of a LogAction value.
     *
     * \param   action      The LogAction value to convert.
     * \return  Returns the string representation of the LogAction.
     **/
    [[nodiscard]]
    static inline constexpr const char * as_string( LoggingEventData::LogAction action ) noexcept;

//////////////////////////////////////////////////////////////////////////
// Constructors / Destructor
//////////////////////////////////////////////////////////////////////////
public:
    LoggingEventData() noexcept;

    /**
     * \brief   Creates the logging event data with specified action.
     *
     * \param   action      The action ID to set in event data.
     **/
    explicit LoggingEventData( LoggingEventData::LogAction action ) noexcept;

    LoggingEventData( const LoggingEventData & src ) noexcept;

    LoggingEventData( LoggingEventData && src ) noexcept;

    ~LoggingEventData() noexcept = default;

    LoggingEventData & operator = ( const LoggingEventData & src ) noexcept;

    LoggingEventData & operator = ( LoggingEventData && src ) noexcept;

//////////////////////////////////////////////////////////////////////////
// Attributes
//////////////////////////////////////////////////////////////////////////
public:

    /**
     * \brief   Returns the value of action set in event data.
     **/
    [[nodiscard]]
    inline LoggingEventData::LogAction logging_action() const noexcept;

    /**
     * \brief   Sets the action in the event data.
     *
     * \param   action      The action to set.
     **/
    inline void set_action( LoggingEventData::LogAction action ) noexcept;

    /**
     * \brief   Returns a pointer to the LogEntry embedded in the message buffer.
     *          Valid only for LogMessage events -- returns nullptr if the message is not allocated.
     **/
    [[nodiscard]]
    inline const areg::LogEntry* log_entry() const noexcept;

    /**
     * \brief   Returns a mutable reference to the pre-built event envelope.
     *          Valid (is_valid() == true) only for LogMessage events.
     **/
    [[nodiscard]]
    inline areg::MessageEnvelope & message() noexcept;

    /**
     * \brief   Returns the pre-built event envelope for forwarding to NetTcpLogger.
     *          Valid (is_valid() == true) only for LogMessage events.
     **/
    [[nodiscard]]
    inline const areg::MessageEnvelope & message() const noexcept;

//////////////////////////////////////////////////////////////////////////
// Member variables
//////////////////////////////////////////////////////////////////////////
private:
    LoggingEventData::LogAction     mAction;    //!< The action to perform.
    areg::MessageEnvelope           mMessage;   //!< Pre-built log message; invalid (null buffer) for non-LogMessage events.
};

//////////////////////////////////////////////////////////////////////////
// Tracing Event and Consumer declaration
//////////////////////////////////////////////////////////////////////////

/**
 * \brief   Declare LoggingEvent class, derived from EventTemplate object,
 *          and LoggingEventConsumer class, derived from TEEventConsumer object
 **/
AREG_DECLARE_EVENT(LoggingEventData, LoggingEvent, LoggingEventConsumer)

//////////////////////////////////////////////////////////////////////////
// LoggingEventData class inline functions
//////////////////////////////////////////////////////////////////////////

inline LoggingEventData::LogAction LoggingEventData::logging_action() const noexcept
{
    return mAction;
}

inline void LoggingEventData::set_action( LoggingEventData::LogAction action ) noexcept
{
    mAction = action;
}

inline const areg::LogEntry* LoggingEventData::log_entry() const noexcept
{
    return mMessage.is_valid() ? reinterpret_cast<const areg::LogEntry*>(mMessage.buffer()) : nullptr;
}

inline areg::MessageEnvelope & LoggingEventData::message() noexcept
{
    return mMessage;
}

inline const areg::MessageEnvelope & LoggingEventData::message() const noexcept
{
    return mMessage;
}

inline constexpr const char * LoggingEventData::as_string( LoggingEventData::LogAction action ) noexcept
{
    switch ( action )
    {
    case LoggingEventData::LogAction::Undefined:
        return "LoggingEventData::LogAction::Undefined";
    case LoggingEventData::LogAction::StartLogs:
        return "LoggingEventData::LogAction::StartLogs";
    case LoggingEventData::LogAction::StopLogs:
        return "LoggingEventData::LogAction::StopLogs";
    case LoggingEventData::LogAction::EnableLogs:
        return "LoggingEventData::LogAction::EnableLogs";
    case LoggingEventData::LogAction::DisableLogs:
        return "LoggingEventData::LogAction::DisableLogs";
    case LoggingEventData::LogAction::SaveScopes:
        return "LoggingEventData::LogAction::SaveScopes";
    case LoggingEventData::LogAction::LogMessage:
        return "LoggingEventData::LogAction::LogMessage";
    case LoggingEventData::LogAction::UpdateScopes:
        return "LoggingEventData::LogAction::UpdateScopes";
    case LoggingEventData::LogAction::QueryScopes:
        return "LoggingEventData::LogAction::QueryScopes";
    default:
        ASSERT(false);
        return "ERR: Undefined LoggingEventData::LogAction value!";
    }
}

} // namespace areg

#endif  // AREG_LOGGING
#endif  // AREG_LOGGING_PRIVATE_LOGGINGEVENT_HPP
