#ifndef AREG_LOGGING_PRIVATE_LOGGINGEVENT_HPP
#define AREG_LOGGING_PRIVATE_LOGGINGEVENT_HPP
/************************************************************************
 * This file is part of the Areg SDK core engine.
 * Areg SDK is dual-licensed under Free open source (Apache version 2.0
 * License) and Commercial (with various pricing models) licenses, depending
 * on the nature of the project (commercial, research, academic or free).
 * You should have received a copy of the Areg SDK license description in LICENSE.txt.
 * If not, please contact to info[at]areg.tech
 *
 * \copyright   (c) 2017-2026 Aregtech UG. All rights reserved.
 * \file        areg/logging/private/LoggingEvent.hpp
 * \ingroup     Areg SDK, Automated Real-time Event Grid Software Development Kit
 * \author      Artak Avetyan
 * \brief       Areg Platform, The logging thread, which is receiving logging events and performs log operations. 
 ************************************************************************/
/************************************************************************
 * Include files.
 ************************************************************************/
#include "areg/base/GEGlobal.h"
#include "areg/component/EventTemplate.hpp"
#include "areg/base/SharedBuffer.hpp"

#if AREG_LOGS

/************************************************************************
 * Dependencies
 ************************************************************************/
namespace areg { class LogMessage; }
namespace areg
{
    struct LogEntry;
}

namespace areg
{
    //////////////////////////////////////////////////////////////////////////
    // LoggingEventData class declaration
    //////////////////////////////////////////////////////////////////////////
    /**
     * \brief   The tracing (or logging) event is triggered each time when application
     *          needs a logging action to be performed. The event is forwarded to a logging thread
     *          for further processing, like configuring logging, output message, etc.
     *          The logging event contains data with the instruction to perform certain actions.
     *          This logging event data is automatically generated by system, when a certain API
     *          is called.
     **/
    class LoggingEventData
    {
    //////////////////////////////////////////////////////////////////////////
    // Internal types and constants
    //////////////////////////////////////////////////////////////////////////
    public:
        /**
         * \brief   LoggingEventData::LogAction
         *          The list of supported actions for logging.
         **/
        enum class LogAction    : uint8_t
        {
            Undefined     //!< Action is undefined, do nothing
            , StartLogs     //!< Action to notify to start logging
            , StopLogs      //!< Action to notify to stop logging
            , EnableLogs    //!< Action to notify to enable logging
            , DisableLogs   //!< Action to notify to stop logging
            , SaveScopes    //!< Action to notify to save scope list
            , LogMessage    //!< Action to output logging message
            , UpdateScopes  //!< Action to update scope priorities
            , QueryScopes   //!< Action to send the list of scopes.
        };

        /**
         * \brief   Converts and returns the string of LoggingEventData::LogAction value
         **/
        static inline const char * getString( LoggingEventData::LogAction action );

    //////////////////////////////////////////////////////////////////////////
    // Constructors / Destructor
    //////////////////////////////////////////////////////////////////////////
    public:
        /**
         * \brief   Creates the logging even data with undefined action
         **/
        LoggingEventData();

        /**
         * \brief   Creates the logging even data with specified action
         * \param   action  The action ID to set in event data
         **/
        explicit LoggingEventData( LoggingEventData::LogAction action );
        
        /**
         * \brief   Creates the logging even data with specified action and data
         * \param   action      The action ID to set in event data
         * \param   dataBuffer  The buffer of data set.
         **/
        LoggingEventData( LoggingEventData::LogAction action, const SharedBuffer & dataBuffer );

        /**
         * \brief   Creates the logging even data with specified action and logging message data
         * \param   action  The action ID to set in event data
         * \param   logData The buffer of logging message data set.
         **/
        LoggingEventData( LoggingEventData::LogAction action, const LogEntry & logData );

        /**
         * \brief   Copies logging event data from given source.
         * \param   src     The source to copy data.
         **/
        LoggingEventData( const LoggingEventData & src );

        /**
         * \brief   Copies logging event data from given source.
         * \param   src     The source to copy data.
         **/
        LoggingEventData( LoggingEventData && src ) noexcept;

        /**
         * \brief   Destructor
         **/
        ~LoggingEventData() = default;

    //////////////////////////////////////////////////////////////////////////
    // Operators
    //////////////////////////////////////////////////////////////////////////
    public:
        /**
         * \brief   Copies data from given source
         * \param   src     The source of data to copy.
         **/
        LoggingEventData & operator = ( const LoggingEventData & src );

        /**
         * \brief   Moves data from given source
         * \param   src     The source of data to move.
         **/
        LoggingEventData & operator = ( LoggingEventData && src ) noexcept;

    //////////////////////////////////////////////////////////////////////////
    // Attributes
    //////////////////////////////////////////////////////////////////////////

        /**
         * \brief   Returns the value of action set in event data.
         **/
        inline LoggingEventData::LogAction getLoggingAction() const;

        /**
         * \brief   Returns the streaming buffer for writing.
         **/
        inline SharedBuffer & getWritableStream();

        /**
         * \brief   Returns the streaming buffer for reading.
         **/
        inline const SharedBuffer & getReadableStream() const;

    //////////////////////////////////////////////////////////////////////////
    // Member variables
    //////////////////////////////////////////////////////////////////////////
    private:
        LoggingEventData::LogAction   mAction;
        SharedBuffer                  mDataBuffer;
    };

    //////////////////////////////////////////////////////////////////////////
    // Tracing Event and Consumer declaration
    //////////////////////////////////////////////////////////////////////////

    /**
     * \brief   Declare LoggingEvent class, derived from EventTemplate object,
     *          and LoggingEventConsumer class, derived from TEEventConsumer object
     **/
    AREG_DECLARE_EVENT(LoggingEventData, LoggingEvent, LoggingEventConsumer)

    //////////////////////////////////////////////////////////////////////////
    // LoggingEventData class inline functions
    //////////////////////////////////////////////////////////////////////////

    inline LoggingEventData::LogAction LoggingEventData::getLoggingAction() const
    {
        return mAction;
    }

    inline SharedBuffer & LoggingEventData::getWritableStream()
    {
        return mDataBuffer;
    }

    inline const SharedBuffer & LoggingEventData::getReadableStream() const
    {
        return mDataBuffer;
    }

    inline const char * LoggingEventData::getString( LoggingEventData::LogAction action )
    {
        switch ( action )
        {
        case LoggingEventData::LogAction::Undefined:
            return "LoggingEventData::LogAction::Undefined";
        case LoggingEventData::LogAction::StartLogs:
            return "LoggingEventData::LogAction::StartLogs";
        case LoggingEventData::LogAction::StopLogs:
            return "LoggingEventData::LogAction::StopLogs";
        case LoggingEventData::LogAction::EnableLogs:
            return "LoggingEventData::LogAction::EnableLogs";
        case LoggingEventData::LogAction::DisableLogs:
            return "LoggingEventData::LogAction::DisableLogs";
        case LoggingEventData::LogAction::SaveScopes:
            return "LoggingEventData::LogAction::SaveScopes";
        case LoggingEventData::LogAction::LogMessage:
            return "LoggingEventData::LogAction::LogMessage";
        case LoggingEventData::LogAction::UpdateScopes:
            return "LoggingEventData::LogAction::UpdateScopes";
        case LoggingEventData::LogAction::QueryScopes:
            return "LoggingEventData::LogAction::QueryScopes";
        default:
            ASSERT(false);
            return "ERR: Undefined LoggingEventData::LogAction value!";
        }
    }

    #endif  // AREG_LOGS
} // namespace areg
#endif  // AREG_LOGGING_PRIVATE_LOGGINGEVENT_HPP
