#ifndef AREG_LOGGING_PRIVATE_SCOPENODES_HPP
#define AREG_LOGGING_PRIVATE_SCOPENODES_HPP
/************************************************************************
 * This file is part of the Areg SDK core engine.
 * Areg SDK is dual-licensed under Free open source (Apache version 2.0
 * License) and Commercial (with various pricing models) licenses, depending
 * on the nature of the project (commercial, research, academic or free).
 * You should have received a copy of the Areg SDK license description in LICENSE.txt.
 * If not, please contact to info[at]areg.tech
 *
 * \copyright   (c) 2017-2026 Aregtech UG. All rights reserved.
 * \file        areg/logging/private/ScopeNodes.hpp
 * \ingroup     Areg SDK, Automated Real-time Event Grid Software Development Kit
 * \author      Artak Avetyan
 * \brief       Areg Platform, The scope nodes classes.
 ************************************************************************/
 /************************************************************************
  * Include files.
  ************************************************************************/
#include "areg/base/GEGlobal.h"
#include "areg/logging/private/ScopeNodeBase.hpp"

#include "areg/base/SortedLinkedList.hpp"

#if AREG_LOGS
/************************************************************************
 * Implemented classes.
 ************************************************************************/
class ScopeLeaf;
class ScopeNode;
class ScopeRoot;
class ConfigManager;

//////////////////////////////////////////////////////////////////////////
// ScopeLeaf class declaration
//////////////////////////////////////////////////////////////////////////
/**
 * \brief   The Leaf node, which has a parent, but does not have children nodes.
 **/
class ScopeLeaf : public ScopeNodeBase
{
//////////////////////////////////////////////////////////////////////////
// Constructors / destructor
//////////////////////////////////////////////////////////////////////////
public:
    /**
     * \brief   Creates a leaf node.
     **/
    ScopeLeaf();
    /**
     * \brief   Copies data from the ScopeNodeBase object.
     *
     * \param   base    The base node to copy data from.
     **/
    explicit ScopeLeaf( const ScopeNodeBase & base );

    /**
     * \brief   Copies data from the given source.
     *
     * \param   src     The source to copy data from.
     **/
    ScopeLeaf( const ScopeLeaf & src );    
    /**
     * \brief   Moves data from the given source.
     *
     * \param   src     The source to move data from.
     **/
    ScopeLeaf( ScopeLeaf && src ) noexcept;

    virtual ~ScopeLeaf() = default;

//////////////////////////////////////////////////////////////////////////
// Operators
//////////////////////////////////////////////////////////////////////////
public:

    /**
     * \brief   Assigns data from the given source. Default implementation.
     *
     * \param   src     The source to assign from.
     **/
    ScopeLeaf & operator = ( const ScopeLeaf & src ) = default;
    /**
     * \brief   Assigns data from the given source. Default implementation.
     *
     * \param   src     The source to assign from.
     * \note    Move overload. Default implementation.
     **/
    ScopeLeaf & operator = ( ScopeLeaf && src ) = default;

//////////////////////////////////////////////////////////////////////////
// Overrides
//////////////////////////////////////////////////////////////////////////
public:

/************************************************************************
 * ScopeNodeBase override
 ************************************************************************/

    /**
     * \brief   Creates a scope name (scope path) by adding the prefix to the node name. If the node
     *          is a leaf, it just adds the name. If it is a node, it adds the name and '_' at the
     *          end to indicate the node.
     *
     * \param   prefix      The prefix to add to the name. In case of root, it is an empty string.
     *                      In case of nodes, it is a path generated by parent nodes.
     **/
    String make_scope_path( const String & prefix ) const override;

    /**
     * \brief   Generates the scope setting and updates in the configuration. If the entry is a
     *          leaf, it generates the full scope name to save in configuration. If the entry is a
     *          node and it has a grouping flag, it generates the scope group to save in
     *          configuration. If the entry is the root and has no child entries, it generates
     *          application scope group entry to save in configuration.
     *
     * \param   config          The instance of ConfigManager to set the scope and priorities to
     *                          save.
     * \param   parentPath      The path name of the parent node. The nodes contain '_' at the end.
     * \return  Returns the number of nodes that have been saved.
     **/
    uint32_t update_config_node( ConfigManager & config, const String & parentPath ) const override;

};

//////////////////////////////////////////////////////////////////////////
// ScopeNode class declaration
//////////////////////////////////////////////////////////////////////////
/**
 * \brief   Concrete scope node with parent, child nodes, and child leafs. Used in hierarchical
 *          scope management for grouping and priority configuration.
 **/
class ScopeNode : public ScopeNodeBase
{
//////////////////////////////////////////////////////////////////////////
// Internal types
//////////////////////////////////////////////////////////////////////////
public:
    using NodeList = SortedLinkedList< ScopeNode>;
    using LeafList = SortedLinkedList< ScopeLeaf>;

//////////////////////////////////////////////////////////////////////////
// Constructors / Destructor
//////////////////////////////////////////////////////////////////////////
public:
    ScopeNode();

    /**
     * \brief   Initializes a node with empty child lists from a base node.
     **/
    explicit ScopeNode( const ScopeNodeBase & base );

    /**
     * \brief   Copy constructor.
     **/
    ScopeNode( const ScopeNode & src );    
    /**
     * \brief   Move constructor.
     **/
    ScopeNode( ScopeNode && src ) noexcept;
    
    virtual ~ScopeNode() = default;

//////////////////////////////////////////////////////////////////////////
// Protected constructor
//////////////////////////////////////////////////////////////////////////
protected:
    /**
     * \brief   Protected constructor for creating root nodes.
     **/
    ScopeNode( ScopeNodeBase::NodeType nodeType, const String & name, uint32_t prio );

//////////////////////////////////////////////////////////////////////////
// Assigning operators
//////////////////////////////////////////////////////////////////////////
public:
    /**
     * \brief   Copy assignment operator.
     **/
    ScopeNode & operator = ( const ScopeNode & src );
    /**
     * \brief   Move assignment operator.
     **/
    ScopeNode & operator = ( ScopeNode && src ) noexcept;

//////////////////////////////////////////////////////////////////////////
// Override
//////////////////////////////////////////////////////////////////////////
public:

/************************************************************************
 * ScopeNodeBase override
 ************************************************************************/

    /**
     * \brief   Creates a child node from a scope path and sets priority flags.
     *
     * \param[in,out] scopePath       The scope path; contains remaining path after operation.
     * \param   prioStates      Logging priority flags to apply.
     * \return  The created child node (node or leaf).
     * \note    Only root and nodes can create children; leafs return invalid node.
     **/
    const ScopeNodeBase & make_child_node( String & scopePath, uint32_t prioStates ) const override;

    /**
     * \brief   Adds or updates a child node. Returns the node and a flag indicating creation (true)
     *          or update (false).
     *
     * \param   child       The child node to add or update.
     * \return  The child node and a boolean flag.
     **/
    std::pair<ScopeNodeBase &, bool> add_child_node( const ScopeNodeBase & child ) override;

    /**
     * \brief   Creates and adds a child node from a scope path, or updates an existing child.
     *
     * \param[in,out] scopePath       The scope path; contains remaining path after operation.
     * \param   prioStates      Logging priority flags to apply.
     * \return  The child node and a boolean flag.
     **/
    std::pair<ScopeNodeBase &, bool> add_child_node( String & scopePath, uint32_t prioStates ) override;

    /**
     * \brief   Generates a scope path by combining prefix with node name.
     *
     * \param   prefix      The prefix to prepend.
     * \return  The generated scope path.
     **/
    String make_scope_path( const String & prefix ) const override;

    /**
     * \brief   Generates a scope configuration string with priority settings.
     *
     * \param   parent      The parent scope name to include in the configuration.
     * \return  The generated configuration string.
     **/
    String make_config_string( const String & parent ) const override;

    /**
     * \brief   Groups and removes child nodes with identical priorities.
     *
     * \return  The number of nodes removed.
     **/
    uint32_t group_child_nodes() override;

    /**
     * \brief   Saves scope priority settings to configuration.
     *
     * \param   config          The ConfigManager instance to update.
     * \param   parentPath      The parent scope path.
     * \return  The number of nodes saved.
     **/
    uint32_t update_config_node(ConfigManager& config, const String & parentPath ) const override;

    /**
     * \brief   Recursively groups child nodes from leaf to root.
     *
     * \return  The total number of nodes grouped.
     **/
    uint32_t group_recursive() override;

    /**
     * \brief   Recursively removes child nodes with the specified priority.
     *
     * \return  The number of nodes removed.
     **/
    uint32_t remove_priority_nodes( uint32_t prioRemove ) override;

    /**
     * \brief   Returns true if the node has no children.
     **/
    bool is_empty() const override;

//////////////////////////////////////////////////////////////////////////
// Attributes and operations
//////////////////////////////////////////////////////////////////////////
public:
    /**
     * \brief   Returns the list of child nodes.
     **/
    inline const ScopeNode::NodeList & nodes() const;

    /**
     * \brief   Returns the list of child leafs.
     **/
    inline const ScopeNode::LeafList & leafs() const;

    /**
     * \brief   Returns the total number of children (nodes and leafs).
     **/
    inline uint32_t child_node_count() const;

//////////////////////////////////////////////////////////////////////////
// Protected members
//////////////////////////////////////////////////////////////////////////
protected:
    //!< The list of child nodes.
    NodeList    mChildNodes;

    //!< The list of child leafs.
    LeafList    mChildLeafs;
};

//////////////////////////////////////////////////////////////////////////
// ScopeRoot class declarations
//////////////////////////////////////////////////////////////////////////
/**
 * \brief   The root node, which does not have a parent, but may have
 *          child nodes and child leafs.
 **/
class ScopeRoot : public ScopeNode
{
//////////////////////////////////////////////////////////////////////////
// Constructor / Destructor
//////////////////////////////////////////////////////////////////////////
public:
    /**
     * \brief   Creates the root node.
     **/
    ScopeRoot();

    virtual ~ScopeRoot() = default;

//////////////////////////////////////////////////////////////////////////
// Override
//////////////////////////////////////////////////////////////////////////
public:

/************************************************************************
 * ScopeNodeBase override
 ************************************************************************/

    /**
     * \brief   Creates a scope name (scope path) by adding the prefix to the node name. If the node
     *          is a leaf, it just adds the name. If it is a node, it adds the name and '_' at the
     *          end to indicate the node.
     *
     * \param   prefix      The prefix to add to the name. In case of root, it is an empty string.
     *                      In case of nodes, it is a path generated by parent nodes.
     **/
    String make_scope_path( const String & prefix ) const override;

    /**
     * \brief   Generates the scope configuration string with the logging priority setting to save
     *          in the file.
     *
     * \param   parent      The parent scope name (or prefix) to add to generated name.
     * \return  Returns generated string, which contains the logging priority setting.
     **/
    String make_config_string( const String & parent ) const override;

    /**
     * \brief   Generates the scope setting and updates in the configuration. If the entry is a
     *          leaf, it generates the full scope name to save in configuration. If the entry is a
     *          node and it has a grouping flag, it generates the scope group to save in
     *          configuration. If the entry is the root and has no child entries, it generates
     *          application scope group entry to save in configuration.
     *
     * \param   config          The instance of ConfigManager to set the scope and priorities to
     *                          save.
     * \param   parentPath      The path name of the parent node. The nodes contain '_' at the end.
     * \return  Returns the number of nodes that have been saved.
     **/
    uint32_t update_config_node(ConfigManager& config, const String & parentPath ) const override;

//////////////////////////////////////////////////////////////////////////
// Forbidden calls
//////////////////////////////////////////////////////////////////////////
private:
    AREG_NOCOPY_NOMOVE( ScopeRoot );
};

//////////////////////////////////////////////////////////////////////////
// ScopeNode class inline methods
//////////////////////////////////////////////////////////////////////////

inline const ScopeNode::NodeList & ScopeNode::nodes() const
{
    return mChildNodes;
}

inline const ScopeNode::LeafList & ScopeNode::leafs() const
{
    return mChildLeafs;
}

inline uint32_t ScopeNode::child_node_count() const
{
    return (mChildLeafs.size( ) + mChildNodes.size( ));
}

#endif  // AREG_LOGS
#endif  // AREG_LOGGING_PRIVATE_SCOPENODES_HPP
