#ifndef AREG_LOGGING_PRIVATE_SCOPENODES_HPP
#define AREG_LOGGING_PRIVATE_SCOPENODES_HPP
/************************************************************************
 * This file is part of the Areg SDK core engine.
 * Areg SDK is dual-licensed under Free open source (Apache version 2.0
 * License) and Commercial (with various pricing models) licenses, depending
 * on the nature of the project (commercial, research, academic or free).
 * You should have received a copy of the Areg SDK license description in LICENSE.txt.
 * If not, please contact to info[at]areg.tech
 *
 * \copyright   (c) 2017-2026 Aregtech UG. All rights reserved.
 * \file        areg/logging/private/ScopeNodes.hpp
 * \ingroup     Areg SDK, Automated Real-time Event Grid Software Development Kit
 * \author      Artak Avetyan
 * \brief       Areg Platform, The scope nodes classes.
 ************************************************************************/
 /************************************************************************
  * Include files.
  ************************************************************************/
#include "areg/base/areg_global.h"
#include "areg/logging/private/ScopeNodeBase.hpp"

#include "areg/base/SortedLinkedList.hpp"

#if AREG_LOGGING
/************************************************************************
 * Implemented classes.
 ************************************************************************/
namespace areg {
    class ScopeLeaf;
    class ScopeNode;
    class ScopeRoot;
    class ConfigManager;
} // namespace areg

namespace areg {

//////////////////////////////////////////////////////////////////////////
// ScopeLeaf class declaration
//////////////////////////////////////////////////////////////////////////
/**
 * \brief   The Leaf node, which has a parent, but does not have children nodes.
 **/
class ScopeLeaf final : public ScopeNodeBase
{
//////////////////////////////////////////////////////////////////////////
// Constructors / destructor
//////////////////////////////////////////////////////////////////////////
public:
    ScopeLeaf();
    /**
     * \brief   Copies data from the ScopeNodeBase object.
     *
     * \param   base    The base node to copy data from.
     **/
    explicit ScopeLeaf( const ScopeNodeBase & base );

    ScopeLeaf( const ScopeLeaf & src );

    ScopeLeaf( ScopeLeaf && src ) noexcept;

    ~ScopeLeaf() override = default;

    ScopeLeaf & operator = ( const ScopeLeaf & src ) = default;

    ScopeLeaf & operator = ( ScopeLeaf && src ) = default;

//////////////////////////////////////////////////////////////////////////
// Attributes and operations
//////////////////////////////////////////////////////////////////////////
public:

    /**
     * \brief   Returns true if this leaf was added via the dot (.) leaf separator, meaning
     *          its name must not be split on '_' and the config path uses '.' before the name.
     **/
    [[nodiscard]]
    inline bool dot_separator() const noexcept;

    /**
     * \brief   Sets whether this leaf uses the dot (.) separator in the config path.
     **/
    inline void set_dot_separator( bool value ) noexcept;

//////////////////////////////////////////////////////////////////////////
// Overrides
//////////////////////////////////////////////////////////////////////////
public:

/************************************************************************
 * ScopeNodeBase override
 ************************************************************************/

    /**
     * \brief   Creates a scope name (scope path) by adding the prefix to the node name. If the node
     *          is a leaf, it just adds the name. If it is a node, it adds the name and '_' at the
     *          end to indicate the node.
     *
     * \param   prefix      The prefix to add to the name. In case of root, it is an empty string.
     *                      In case of nodes, it is a path generated by parent nodes.
     **/
    String make_scope_path( const String & prefix ) const final;

    /**
     * \brief   Generates the scope setting and updates in the configuration. If the entry is a
     *          leaf, it generates the full scope name to save in configuration. If the entry is a
     *          node and it has a grouping flag, it generates the scope group to save in
     *          configuration. If the entry is the root and has no child entries, it generates
     *          application scope group entry to save in configuration.
     *
     * \param   config          The instance of ConfigManager to set the scope and priorities to save.
     * \param   parentPath      The path name of the parent node. The nodes contain '_' at the end.
     * \return  Returns the number of nodes that have been saved.
     **/
    uint32_t update_config_node( ConfigManager & config, const String & parentPath ) const final;

//////////////////////////////////////////////////////////////////////////
// Member variables
//////////////////////////////////////////////////////////////////////////
private:
    //!< True if this leaf was inserted via the dot ('.') leaf separator in the scope name.
    bool    mDotSeparator { false };
};

//////////////////////////////////////////////////////////////////////////
// ScopeLeaf inline methods
//////////////////////////////////////////////////////////////////////////

inline bool ScopeLeaf::dot_separator() const noexcept
{
    return mDotSeparator;
}

inline void ScopeLeaf::set_dot_separator( bool value ) noexcept
{
    mDotSeparator = value;
}

//////////////////////////////////////////////////////////////////////////
// ScopeNode class declaration
//////////////////////////////////////////////////////////////////////////
/**
 * \brief   Concrete scope node with parent, child nodes, and child leafs. Used in hierarchical
 *          scope management for grouping and priority configuration.
 **/
class ScopeNode : public ScopeNodeBase
{
//////////////////////////////////////////////////////////////////////////
// Internal types
//////////////////////////////////////////////////////////////////////////
public:
    using NodeList = SortedLinkedList< ScopeNode>;
    using LeafList = SortedLinkedList< ScopeLeaf>;

//////////////////////////////////////////////////////////////////////////
// Constructors / Destructor
//////////////////////////////////////////////////////////////////////////
public:
    ScopeNode();

    /**
     * \brief   Initializes a node with empty child lists from a base node.
     **/
    explicit ScopeNode( const ScopeNodeBase & base );

    ScopeNode( const ScopeNode & src );    

    ScopeNode( ScopeNode && src ) noexcept;
    
    ~ScopeNode() override = default;

//////////////////////////////////////////////////////////////////////////
// Protected constructor
//////////////////////////////////////////////////////////////////////////
protected:
    /**
     * \brief   Protected constructor for creating root nodes.
     **/
    ScopeNode( ScopeNodeBase::NodeType nodeType, const String & name, uint32_t prio );

//////////////////////////////////////////////////////////////////////////
// Assigning operators
//////////////////////////////////////////////////////////////////////////
public:

    ScopeNode & operator = ( const ScopeNode & src );

    ScopeNode & operator = ( ScopeNode && src ) noexcept;

//////////////////////////////////////////////////////////////////////////
// Override
//////////////////////////////////////////////////////////////////////////
public:

/************************************************************************
 * ScopeNodeBase override
 ************************************************************************/

    /**
     * \brief   Generates a scope path by combining prefix with node name.
     *
     * \param   prefix      The prefix to prepend.
     * \return  The generated scope path.
     **/
    String make_scope_path( const String & prefix ) const override;

    /**
     * \brief   Generates a scope configuration string with priority settings.
     *
     * \param   parent      The parent scope name to include in the configuration.
     * \return  The generated configuration string.
     **/
    String make_config_string( const String & parent ) const override;

    /**
     * \brief   Saves scope priority settings to configuration.
     *
     * \param   config          The ConfigManager instance to update.
     * \param   parentPath      The parent scope path.
     * \return  The number of nodes saved.
     **/
    uint32_t update_config_node(ConfigManager& config, const String& parentPath) const override;

    /**
     * \brief   Creates a child node from a scope path and sets priority flags.
     *
     * \param[in,out] scopePath       The scope path; contains remaining path after operation.
     * \param   prioStates      Logging priority flags to apply.
     * \return  The created child node (node or leaf).
     * \note    Only root and nodes can create children; leafs return invalid node.
     **/
    const ScopeNodeBase & make_child_node( String & scopePath, uint32_t prioStates ) const final;

    /**
     * \brief   Adds or updates a child node. Returns the node and a flag indicating creation (true)
     *          or update (false).
     *
     * \param   child       The child node to add or update.
     * \return  The child node and a boolean flag.
     **/
    std::pair<ScopeNodeBase &, bool> add_child_node( const ScopeNodeBase & child ) final;

    /**
     * \brief   Creates and adds a child node from a scope path, or updates an existing child.
     *
     * \param[in,out] scopePath       The scope path; contains remaining path after operation.
     * \param   prioStates      Logging priority flags to apply.
     * \return  The child node and a boolean flag.
     **/
    std::pair<ScopeNodeBase &, bool> add_child_node( String & scopePath, uint32_t prioStates ) final;

    /**
     * \brief   Groups and removes child nodes with identical priorities.
     *
     * \return  The number of nodes removed.
     **/
    uint32_t group_child_nodes() final;

    /**
     * \brief   Recursively groups child nodes from leaf to root.
     *
     * \return  The total number of nodes grouped.
     **/
    uint32_t group_recursive() final;

    /**
     * \brief   Recursively removes child nodes with the specified priority.
     *
     * \return  The number of nodes removed.
     **/
    uint32_t remove_priority_nodes( uint32_t prioRemove ) noexcept final;

    /**
     * \brief   Returns true if the node has no children.
     **/
    bool is_empty() const noexcept final;

//////////////////////////////////////////////////////////////////////////
// Attributes and operations
//////////////////////////////////////////////////////////////////////////
public:
    /**
     * \brief   Returns the list of child nodes.
     **/
    [[nodiscard]]
    inline const ScopeNode::NodeList & nodes() const noexcept;

    /**
     * \brief   Returns the list of child leafs.
     **/
    [[nodiscard]]
    inline const ScopeNode::LeafList & leafs() const noexcept;

    /**
     * \brief   Returns the total number of children (nodes and leafs).
     **/
    [[nodiscard]]
    inline uint32_t child_node_count() const noexcept;

//////////////////////////////////////////////////////////////////////////
// Protected members
//////////////////////////////////////////////////////////////////////////
protected:
    //!< The list of child nodes.
    NodeList    mChildNodes;

    //!< The list of child leafs.
    LeafList    mChildLeafs;
};

//////////////////////////////////////////////////////////////////////////
// ScopeRoot class declarations
//////////////////////////////////////////////////////////////////////////
/**
 * \brief   The root node, which does not have a parent, but may have
 *          child nodes and child leafs.
 **/
class ScopeRoot final : public ScopeNode
{
//////////////////////////////////////////////////////////////////////////
// Constructor / Destructor
//////////////////////////////////////////////////////////////////////////
public:
    ScopeRoot();

    ~ScopeRoot() override = default;

//////////////////////////////////////////////////////////////////////////
// Override
//////////////////////////////////////////////////////////////////////////
public:

/************************************************************************
 * ScopeNodeBase override
 ************************************************************************/

    /**
     * \brief   Creates a scope name (scope path) by adding the prefix to the node name. If the node
     *          is a leaf, it just adds the name. If it is a node, it adds the name and '_' at the
     *          end to indicate the node.
     *
     * \param   prefix      The prefix to add to the name. In case of root, it is an empty string.
     *                      In case of nodes, it is a path generated by parent nodes.
     **/
    String make_scope_path( const String & prefix ) const final;

    /**
     * \brief   Generates the scope configuration string with the logging priority setting to save
     *          in the file.
     *
     * \param   parent      The parent scope name (or prefix) to add to generated name.
     * \return  Returns generated string, which contains the logging priority setting.
     **/
    String make_config_string( const String & parent ) const final;

    /**
     * \brief   Generates the scope setting and updates in the configuration. If the entry is a
     *          leaf, it generates the full scope name to save in configuration. If the entry is a
     *          node and it has a grouping flag, it generates the scope group to save in
     *          configuration. If the entry is the root and has no child entries, it generates
     *          application scope group entry to save in configuration.
     *
     * \param   config          The instance of ConfigManager to set the scope and priorities to
     *                          save.
     * \param   parentPath      The path name of the parent node. The nodes contain '_' at the end.
     * \return  Returns the number of nodes that have been saved.
     **/
    uint32_t update_config_node(ConfigManager& config, const String & parentPath ) const final;

//////////////////////////////////////////////////////////////////////////
// Forbidden calls
//////////////////////////////////////////////////////////////////////////
private:
    AREG_NOCOPY_NOMOVE( ScopeRoot );
};

//////////////////////////////////////////////////////////////////////////
// ScopeNode class inline methods
//////////////////////////////////////////////////////////////////////////

inline const ScopeNode::NodeList & ScopeNode::nodes() const noexcept
{
    return mChildNodes;
}

inline const ScopeNode::LeafList & ScopeNode::leafs() const noexcept
{
    return mChildLeafs;
}

inline uint32_t ScopeNode::child_node_count() const noexcept
{
    return (mChildLeafs.size( ) + mChildNodes.size( ));
}

} // namespace areg

#endif  // AREG_LOGGING
#endif  // AREG_LOGGING_PRIVATE_SCOPENODES_HPP
