areg_SRC += \
    $(areg_BASE)/appbase/private/Application.cpp			\
    $(areg_BASE)/appbase/private/configure.cpp				\
    $(areg_BASE)/appbase/private/NEApplication.cpp			\
    $(areg_BASE)/appbase/private/posix/ApplicationPosix.cpp \
    $(areg_BASE)/appbase/private/win32/ApplicationWin32.cpp	\
