include $(areg_BASE)/appbase/private/posix/Makefile
include $(areg_BASE)/appbase/private/win32/Makefile

areg_SRC += \
    $(areg_BASE)/appbase/private/Application.cpp			\
    $(areg_BASE)/appbase/private/configure.cpp				\
    $(areg_BASE)/appbase/private/NEApplication.cpp			\
