name: macOS Build
on:
  push:         # Keep empty to run on each branch when push the code. Otherwise use branches: [ master ]
    branches: [feature/652-build-sources-on-macos]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


jobs:
  build:
    runs-on: macos-latest
    steps:

      - name: Checkout Areg SDK source codes
        uses: actions/checkout@v6

      - name: Setup Java JDK to run code generator
        uses: actions/setup-java@v5.1.0
        with: 
          java-version: 17
          java-package: jre
          distribution: temurin

      - name: Ensure Xcode CLI Tools
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: create build directory
        working-directory: ${{github.workspace}}
        run: mkdir build

      - name: Configure CMake for macOS native
        working-directory: ${{github.workspace}}
        run: cmake -S . -B ./build

      - name: Build with CMake
        working-directory: ${{github.workspace}}
        run: cmake --build ./build -j16
